;P

[Include Config]
include = Config.ini
[Include Main]
include = Main.ini
; [Include Keybindings]
; include = Keybindings.ini
[Include hic_sunt_dracones\TransparencyAnchors]
include = hic_sunt_dracones\TransparencyAnchors.ini
[Include hic_sunt_dracones\TransparencyDriver]
include = hic_sunt_dracones\TransparencyDriver.ini
[Include hic_sunt_dracones\TransparencyDiffusePixelShaderRegex]
include = hic_sunt_dracones\DiffusePixelShaderRegex.ini
[Include hic_sunt_dracones\TransparencyOutlinePixelShaderRegex]
include = hic_sunt_dracones\OutlinePixelShaderRegex.ini
[Include hic_sunt_dracones\LegacyCommands]
include = hic_sunt_dracones\LegacyCommands.ini
