namespace = TexFx

; Variables & Resources ------------------------------
[Constants]
global $version = 1.0661
global $texfx_on = 1
global $outline_mode_supercide
global $back_render_supercide
global $use_default_shader = -1
global $glow_intensity = 1
global $bloom_intensity = 1
global $glow = 1
global $bloom = 1
global $hue = 0
global $sat = 0
global $val = 0
global $alpha = 0
; Experimental Transparency
global $drawn = 0
global $internal_control
; DrawIndexed Params
global $_1 = 0
global $_2 = 0
global $_3 = 0
;
global $pixels = 0

; Present --------------------------------------------
[Present]
if $costume_mods
    run = CommandListClearIV
    post run = CommandListClearFakes
    post run = CommandListSetFlags
    post $drawn = -1
    post x69 = 0
    post $use_default_shader = -1
endif

[CommandListSetFlags]
; Lite Version
x69 = !($texfx_on % 2) + ($seizure % 2)*2 + ((($outline_mode + $outline_mode_supercide) > 0) % 2)*8 + ($uncensor % 3)*16
; Long Version
; local $__message = 0
; local $__a = !($texfx_on % 2)
; local $__b = $seizure % 2
; local $__c = (($outline_mode + $outline_mode_supercide) > 0) % 2
; local $__d = $uncensor % 3
; $__message = $__a + $__b*2 + 0*4 + $__c*8 + $__d*16
; x69 = $__message

; Commandlists ---------------------------------------
[CommandListSetIV]
run = CommandListSetInstanceValues
[CommandListSetInstanceValues]
y69 = $glow*($glow_intensity==1)+$glow_intensity*($glow_intensity!=1)
z69 = $bloom*($bloom_intensity==1)+$bloom_intensity*($bloom_intensity!=1)
w69 = $alpha
; x70 = 0
y70 = $hue
z70 = $sat
w70 = $val
run = CommandListSetFlags

[CommandListClearIV]
run = CommandListClearInstanceValues
[CommandListClearInstanceValues]
$bloom_intensity = 1
$glow_intensity = 1
$alpha = 0
$bloom = 1
$glow = 1
$hue = 0
$sat = 0
$val = 0
y69 = 1
z69 = 1
w69 = 0
; x70 = 0
y70 = 0
z70 = 0
w70 = 0

; I'm keeping my Typo Lupo.
[CommandListTransparecny_new]
run = CommandList_DiffuseSecondDraw

[CommandListT]
$use_default_shader = 0
run = CommandListTransparecny_new
$use_default_shader = -1
[CommandListTransparency]
$use_default_shader = 0
run = CommandListTransparecny_new
$use_default_shader = -1

[CommandListC]
run = CommandListComponent
[CommandListComponent]
run = CommandList_DiffuseSecondDraw
run = CommandListDrawFromVars
run = CommandListClearDrawArgs

; Force Outlines for Transparency On/Off.
[CommandListFO.E]
$outline_mode_supercide = 1
[CommandListFO.Enable]
$outline_mode_supercide = 1
[CommandListForceOutline.Enable]
$outline_mode_supercide = 1

[CommandListFO.D]
$outline_mode_supercide = -1
[CommandListFO.Disable]
$outline_mode_supercide = -1
[CommandListForceOutline.Disable]
$outline_mode_supercide = -1

; Force Back Face Transparency On/Off.
[CommandListBFT.E]
$back_render_supercide = 1
[CommandListBFT.Enable]
$back_render_supercide = 1
[CommandListBackFaceTransparency.Enable]
$back_render_supercide = 1

[CommandListBFT.D]
$back_render_supercide = -1
[CommandListBFT.Disable]
$back_render_supercide = -1
[CommandListBackFaceTransparency.Disable]
$back_render_supercide = -1
