[TextureOverrideFace]
hash = 
ps-t71 = FaceCutoutMask
run = CommandList\TexFx\Face

[TextureOverrideHair]
hash = 
run = CommandList\TexFx\AnimeBangs

[CommandListAnimeBangs]
$animebangs = 1

[CommandListFace]
run = CustomShader
; backup render targets
Resourceo0 = ref o0
Resourceo1 = ref o1
Resourceo2 = ref o2

;replace with custom
o0 = ResourceBangs_o0
o1 = ResourceBangs_o1
o2 = ResourceBangs_o2

ps-t71 = null

;draw copy of bangs with inverted or without mask
drawindexed = auto

o0 = ref Resourceo0
o1 = ref Resourceo1
o2 = ref Resourceo2
