namespace = TexFx

[Constants]
;DrawIndexed Params
global $_1 = 0
global $_2 = 0
global $_3 = 0

[CommandListC]
run = CommandListComponent.0
[CommandListC.0]
run = CommandListComponent.0
[CommandListComponent]
run = CommandListComponent.0
[CommandListComponent.0]
run = CommandListDrawFromVars
run = CommandList_DiffuseSecondDraw
run = CommandListClearDrawArgs
;run = CommandListClearInstanceValues
;run = CommandListResetResources

[Resourceo1Back]
[Resourceo2Back]

[CommandListC.1]
run = CommandListComponent.1
[CommandListComponent.1]
run = CommandListDrawFromVars
run = CommandList_DiffuseSecondDraw
run = CommandListClearDrawArgs
run = CommandListClearInstanceValues
run = CommandListResetResources

[CommandListCN.0]
run = CommandListComponentNatlan.0
[CommandListCNat.0]
run = CommandListComponentNatlan.0
[CommandListComponentNatlan.0]
run = CommandListDrawFromVars
run = CommandList_DiffuseSecondDraw
run = CommandListClearDrawArgs
run = CommandListClearInstanceValues
run = CommandListResetResources


[CommandListCN]
run = CommandListComponentNatlan.1
[CommandListCNat]
run = CommandListComponentNatlan.1
[CommandListComponentNatlan]
run = CommandListComponentNatlan.1
[CommandListCN.1]
run = CommandListComponentNatlan.1
[CommandListCNat.1]
run = CommandListComponentNatlan.1
[CommandListComponentNatlan.1]
run = CommandListDrawFromVars
run = CommandList_DiffuseSecondDraw
run = CommandListClearDrawArgs
run = CommandListClearInstanceValues
run = CommandListResetResources
