namespace = TexFx

[ShaderRegexDiffuseTransparency]
shader_model = ps_4_0 ps_5_0
;filter_index = 4243.05
temps = ini tex69 tex72 dim storage color o1 o2 texcoord
; if ps-t69 === 0
;     ;dump = o0 dds
;     ; $counter = $counter + 1
;     run = CommandListClearInstanceValues
; endif
;


;Cute regex to match (almost) every character diffuse shader and outline
[ShaderRegexDiffuseTransparency.Pattern]
(?(DEFINE)
    (?'fl'-?\d+\.?\d{0,6})
    (?'cmp'\.[xyzw]{1,4})
    (?'l1'l\((?&fl)\))
    (?'l4'l\((?&fl),\h(?&fl),\h(?&fl),\h(?&fl)\))
    (?'r'-?r\d\d?\.[xyzw]{1,4})
    (?'v'-?v\d\d?\.[xyzw]{1,4})
    (?'rv'-?[rv]\d\d?\.[xyzw]{1,4})
    (?'cb'-?cb\d\[\d+\]\.\w{1,4})
    (?'icb'icb\[-?r\d\d?\.[xyzw]{1,4}\h\+\h-?\d+\]\.[xyzw]{1,4})
    (?'dcl2d'dcl_resource_texture2d\h\(float,float,float,float\)\ht\d\d?\n)
    (?'dclin'dcl_input_ps[\w\h]+(?&v)\n)
    (?'s2d'sample_[b_]{0,2}(aoffimmi_)?indexable(\(\d,\d,\d\))?\(texture2d\)\(float,float,float,float\))
    ((?'oop'\w+\h(?'oo1'o1(?&cmp))|(?'oo2'o2(?&cmp))|(?'oo4'o4(?&cmp)|o\d(?&cmp)),\h.+))
    (?'br'(?:.*\n)*?)
)(?s)
(?'MatchDiffuse'
(?&dcl2d){3,}
(?&dclin){3,}
(?'backface'dcl_input_ps_sgv\hconstant\hv\d{1,2}\.x,\his_front_face\n)?
dcl_output\ho0\.xyzw\n
dcl_output\ho1\.xyzw\n
dcl_output\ho2\.xyzw\n
dcl_output\ho3\.x\n
dcl_output\ho4\.x\n
dcl_output\ho5\.x\n
dcl_temps\h\d\d?.*)
(?'ModestyB'
\h*if_nz\h(?&r)\n
\h+div\h(?&r),\h(?&v),\h(?&v)\n
\h+mul\h(?&r),\h(?&r),\h(?&cb)\n
\h+mul\h(?&r),\h(?&r),\h(?&l4)\n
\h+ge\h(?&r),\h(?&r),\h(?&r)\n
\h+frc\h(?&r),\h\|(?&r)\|\n
\h+movc\h(?&r),\h(?&r),\h(?&r),\h(?&r)\n
\h+mul\h(?&r),\h(?&r),\h(?&l4)\n
\h+ftou\h(?&r),\h(?&r)\n
\h+dp\d\h(?&r),\h(?&cb),\h(?&icb)\n
\h+dp\d\h(?&r),\h(?&cb),\h(?&icb)\n
\h+dp\d\h(?&r),\h(?&cb),\h(?&icb)\n
\h+dp\d\h(?&r),\h(?&cb),\h(?&icb)\n
\h+dp\d\h(?&r),\h(?&r),\h(?&icb)\n
\h+mad\h(?&r),\h((?&cb)|(?&r)),\h(?&l1),\h(?&r)\n
\h+add\h(?&r),\h(?&r),\h(?&l1)\n
\h+lt\h(?&r),\h(?&r),\h(?&l1)\n)
(?'Modesty'\h*discard_n?z\h(?&r)\n)
(?'TillTexcord'.*)
(?'sample'(?&s2d)\h-?r\d\d?\.[xyzw]{2,4},\h(?'TexcoordX'-?[rv]\d\d?\.[xyz][yzw][xyz][xyz]),\ht[016]\.[xyzw]{3,4},\h(?'sampler's\d)(,\h\w\d+(\.[xyzw]+)?)?)
;\h(?'Glow'(?'GlowHead'.*)sqrt\ho1\.w,\h(?'GlowReg'(?&r)))?
;\h(?'o2Pick'(?'o2head'.*)movc\ho2\.z,\h(?'o2PickReg'(?&r),\h(?&r),\h(?&r)))?
;\h(?'Tillo1'.*)(?'o1line'mov\ho1\.(?'o1var'[xyzw]{3,4},\h(?&r)))
; (?'Tillo2'.*)(?'o2line'mov\ho2\.(?'o2var'[xyzw]{2,4},\h(?&r)))
(?'Tillo2'.*mov\ho2\.[xyzw]{2,4},\h(?&r))
; (?'Tillo4'.*)(?'Bloom'mov\ho4.x,\h)(?'BloomReg'(?&r))
(?'Tillo4'.*mov\ho4.x,\h(?&r))
(?'TillRet'.*)
ret

[ShaderRegexDiffuseTransparency.InsertDeclarations]
dcl_resource_texture1d (float,float,float,float) t120
dcl_resource_texture2d (float,float,float,float) t72
dcl_resource_texture2d (float,float,float,float) t69
dcl_input_ps_siv linear noperspective v21.xy, position
dcl_input_ps_sgv constant v20.x, is_front_face
dcl_output o6.xyzw

;Inserts a discard statement if any pixel from our ps-t69 texture is not OPAQUE
[ShaderRegexDiffuseTransparency.Pattern.Replace]
${MatchDiffuse}
;discard_z l(0)\n
${ModestyB}
ld_indexable(texture1d)(float,float,float,float) ${ini}.xyzw, l(69,0), t120.xyzw\n
if_nz ${ini}.z\n
	${Modesty}
endif\n
${TillTexcord}\n
mov ${texcoord}.xyzw, ${TexcoordX}\n
${sample}
; ${Glow:+${Glow}\n:}
; ${o2Pick:+mov ${o2}.z, ${storage}.z\n
; ${o2Pick}:}
; ;${Tillo2CBPick}\n
; ${Tillo1}${o1line}\n
${Tillo2}
;${o2line}\n
${Tillo4}
; ; mov ${storage}.w, ${BloomReg}\n
; ${Bloom}${BloomReg}\n
${TillRet}
;mul o1.y, o1.y, l(0.2)\n
; EXPERIMENTAL
ld_indexable(texture1d)(float,float,float,float) ${ini}.xyzw, l(69,0), t120.xyzw\n
ld_indexable(texture1d)(float,float,float,float) r0.xyzw, l(70,0), t120.xyzw\n
resinfo_indexable(texture2d)(float,float,float,float) ${dim}.xyyy, l(0), t69.xyzw\n
;mov ${tex69}.xyzw, l(0.000000, 0.000000, 0.000000, 1.000000)\n
;max ${dim}.xy, ${ini}.yy, ${dim}.xy\n
if_nz ${dim}.xy\n
\t  sample_indexable(texture2d)(float,float,float,float) ${tex69}.xyzw, ${texcoord}.xyzw, t69.xyzw, ${sampler}\n
;\t  sample_indexable(texture2d)(float,float,float,float) ${tex72}.xyzw, ${texcoord}.xyzw, t72.xyzw, ${sampler}\n

eq r0.w, ${tex69}.x, l(1.000000)\n
discard_nz r0.w\n
\t  add ${ini}.x, ${ini}.x, -l(5.0)\n
\t  if_z ${ini}.x\n
eq r0.w, ${tex69}.x, l(0.000000)\n
discard_nz r0.w\n
;\t\t    mov o1.xyz, ${tex69}.xyzx\n
\t\t    eq r0.w, r0.x, l(2.0)\n
\t\t    if_z r0.w\n
\t\t\t    add o6.x, ${tex72}.x, ${tex69}.x\n
\t\t\t    mov o6.y, l(0.0)\n
\t\t    else\n
\t\t\t     add o6.y, ${tex72}.y, ${tex69}.x\n
\t\t\t     mov o6.x, l(0.0)\n
\t\t    endif\n
\t\t    mov o6.w, ${tex69}.x\n
utof r0.z, v20.x\n
discard_z r0.z\n
mad r0.z, r0.z, l(0.5), l(0.33333)\n
mov o6.z, r0.z\n
\t  else\n
\t\t    discard_nz ${tex69}.x\n
\t  endif\n
endif\n
ret\n

; ld_indexable(texture1d)(float,float,float,float) ${ini}.xyzw, l(69,0), t120.xyzw\n
; if_z ${ini}.y\n
; \t	resinfo_indexable(texture2d)(float,float,float,float) ${dim}.xyyy, l(0), t69.xyzw\n
; ;\t  max ${dim}.xy, ${ini}.xx, ${dim}.xy\n
; \t	if_nz ${dim}.xy\n
; \t\t    ld_indexable(texture1d)(float,float,float,float) ${ini}.xyzw, l(70,0), t120.xyzw\n
; ; \t\t    mul r0.xy%1, ${Texcoord}, l(0.99999,0.99999)\n
; ; \t\t    mul ${dim}.xyyy, ${dim}.xyyy, r0.xyyy\n
; ; \t\t    mov ${dim}.zw, l(0,0)\n
; ; \t\t    ftoi ${dim}.xyyy, ${dim}.xyyy\n
; ; \t\t    ld_indexable(texture2d)(float,float,float,float) ${tex69}.xyzw, ${dim}.xyzy, t69.xyzw\n
; \t\t    sample_aoffimmi_indexable(1,1,1)(texture2d)(float,float,float,float) ${tex69}.xyzw, ${texcoord}.xyzw, t69.xyzw, s15\n
; \t\t    mul ${tex69}.yz, ${tex69}.yz, ${ini}.yz\n
; \t\t    add ${tex69}.yz, ${tex69}.yz, ${storage}.wx\n
; ; Alpha Channel
; ;\t\t    max ${tex69}.xyzw, ${tex69}.xyzw, ${ini}.xxxx\n
; \t\t    if_nz ${tex69}.w\n
; \t\t\t      ld_indexable(texture1d)(float,float,float,float) ${color}.xyzw, l(71,0), t120.xyzw\n
; \t\t\t      lt ${tex69}.w, ${tex69}.w, l(0.25)\n
; \t\t\t      min ${tex69}.w, ${tex69}.w, ${color}.w\n
; ;\t\t\t      max ${tex69}.w, ${tex69}.w,  ${ini}.x\n
; \t\t\t      if_nz ${tex69}.w\n
; ;
; ; o1
; ;
; \t\t\t\t		mov r0.zw, l(0,0,-1.000000,0.666667)\n
; \t\t\t\t		mov r1.zw, l(0,0,0,-0.333333)\n
; \t\t\t\t		mov r2.xyzw, ${o1}.xyzx\n
; \t\t\t\t		mov r0.xy, r2.zyzz\n
; \t\t\t\t		mov r1.xy, r0.yxyy\n
; \t\t\t\t		lt r2.y, r0.y, r2.z\n
; \t\t\t\t		movc r0.xyzw, r2.yyyy, r0.xyzw, r1.xyzw\n
; \t\t\t\t		lt r1.x, r2.x, r0.x\n
; \t\t\t\t		mov r3.xyz, r0.xywx\n
; \t\t\t\t		mov r3.w, r2.x\n
; \t\t\t\t		mov r0.xyw, r3.wywx\n
; \t\t\t\t		movc r0.xyzw, r1.xxxx, r3.xyzw, r0.xyzw\n
; \t\t\t\t		min r1.x, r0.y, r0.w\n
; \t\t\t\t		add r1.x, r0.x, -r1.x\n
; \t\t\t\t		mad r1.y, r1.x, l(6.000000), l(0.000000)\n
; \t\t\t\t		add r0.y, -r0.y, r0.w\n
; \t\t\t\t		div r0.y, r0.y, r1.y\n
; \t\t\t\t		add r0.y, r0.y, r0.z\n
; ; HUE
; \t\t\t\t		add r0.z, ${color}.x, |r0.y|\n
; \t\t\t\t		ge r0.w, r0.z, -r0.z\n
; \t\t\t\t		frc r0.z, |r0.z|\n
; \t\t\t\t		movc r0.z, r0.w, r0.z, -r0.z\n
; \t\t\t\t		ge r0.w, |r0.y|, l(0.266000)\n
; \t\t\t\t        mov r0.w, l(1.0)\n
; \t\t\t\t		movc r0.y, r0.w, r0.z, |r0.y|\n
; \t\t\t\t		add r0.yzw, r0.yyyy, l(0.000000, 1.000000, 0.666667, 0.333333)\n
; \t\t\t\t		frc r0.yzw, r0.yyzw\n
; \t\t\t\t		mad r0.yzw, r0.yyzw, l(0.000000, 6.000000, 6.000000, 6.000000), l(0.000000, -3.000000, -3.000000, -3.000000)\n
; \t\t\t\t		add_sat r0.yzw, |r0.yyzw|, l(0.000000, -1.000000, -1.000000, -1.000000)\n
; \t\t\t\t		add r0.yzw, r0.yyzw, l(0.000000, -1.000000, -1.000000, -1.000000)\n
; \t\t\t\t		add r1.y, r0.x, l(0.000000)\n
; ; VAL
; \t\t\t\t		add r0.x, r0.x, ${color}.z\n
; \t\t\t\t		div r1.x, r1.x, r1.y\n
; ; SAT
; \t\t\t\t		add r1.x, r1.x, ${color}.y\n
; \t\t\t\t		mad r0.yzw, r1.xxxx, r0.yyzw, l(0.000000, 1.000000, 1.000000, 1.000000)\n
; \t\t\t\t		mul o1.xyz, r0.yzwy, r0.xxxx\n
; ;
; ; o2
; ;
; \t\t\t\t		mov r0.zw, l(0,0,-1.000000,0.666667)\n
; \t\t\t\t		mov r1.zw, l(0,0,0,-0.333333)\n
; \t\t\t\t		mov r2.xyzw, ${o2}.xywz\n
; \t\t\t\t		mov r0.xy, r2.zyzz\n
; \t\t\t\t		mov r1.xy, r0.yxyy\n
; \t\t\t\t		lt r2.y, r0.y, r2.z\n
; \t\t\t\t		movc r0.xyzw, r2.yyyy, r0.xyzw, r1.xyzw\n
; \t\t\t\t		lt r1.x, r2.x, r0.x\n
; \t\t\t\t		mov r3.xyz, r0.xywx\n
; \t\t\t\t		mov r3.w, r2.x\n
; \t\t\t\t		mov r0.xyw, r3.wywx\n
; \t\t\t\t		movc r0.xyzw, r1.xxxx, r3.xyzw, r0.xyzw\n
; \t\t\t\t		min r1.x, r0.y, r0.w\n
; \t\t\t\t		add r1.x, r0.x, -r1.x\n
; \t\t\t\t		mad r1.y, r1.x, l(6.000000), l(0.000000)\n
; \t\t\t\t		add r0.y, -r0.y, r0.w\n
; \t\t\t\t		div r0.y, r0.y, r1.y\n
; \t\t\t\t		add r0.y, r0.y, r0.z\n
; ; HUE
; \t\t\t\t		add r0.z, ${color}.x, |r0.y|\n
; \t\t\t\t		ge r0.w, r0.z, -r0.z\n
; \t\t\t\t		frc r0.z, |r0.z|\n
; \t\t\t\t		movc r0.z, r0.w, r0.z, -r0.z\n
; \t\t\t\t		ge r0.w, |r0.y|, l(0.266000)\n
; \t\t\t\t		movc r0.y, r0.w, r0.z, |r0.y|\n
; \t\t\t\t		add r0.yzw, r0.yyyy, l(0.000000, 1.000000, 0.666667, 0.333333)\n
; \t\t\t\t		frc r0.yzw, r0.yyzw\n
; \t\t\t\t		mad r0.yzw, r0.yyzw, l(0.000000, 6.000000, 6.000000, 6.000000), l(0.000000, -3.000000, -3.000000, -3.000000)\n
; \t\t\t\t		add_sat r0.yzw, |r0.yyzw|, l(0.000000, -1.000000, -1.000000, -1.000000)\n
; \t\t\t\t		add r0.yzw, r0.yyzw, l(0.000000, -1.000000, -1.000000, -1.000000)\n
; \t\t\t\t		add r1.y, r0.x, l(-1)\n
; ; VAL
; \t\t\t\t		add r0.x, r0.x, ${color}.z\n
; \t\t\t\t		div r1.x, r1.x, r1.y\n
; ; SAT
; \t\t\t\t		add r1.x, r1.x, ${color}.y\n
; \t\t\t\t		mad r0.yzw, r1.xxxx, r0.yyzw, l(0.000000, 1.000000, 1.000000, 1.000000)\n
; \t\t\t\t		mul o2.xyz, r0.yzwy, r0.xxxx\n

; \t\t\t      endif\n
; \t\t    endif\n
; \t\t    sample_aoffimmi_indexable(1,1,1)(texture2d)(float,float,float,float) r0.xyzw, ${texcoord}.xyzw, t69.xyzw, s15\n
; ; Green Channel
; \t\t    if_nz r0.y\n
; \t\t\t		mov o1.w, ${tex69}.y\n
; \t\t	endif\n
; ; Blue Channel
; \t\t	if_nz r0.z\n
; \t\t\t		mov o4.x, ${tex69}.z\n
; \t\t	endif\n
; ; Red Channel
; \t\t	discard_nz r0.x\n
; \t  endif\n
; endif\n

; ; EXPERIMENTAL
; add ${ini}.y, ${ini}.y, l(-5.0)\n
; if_z ${ini}.y\n
;     \t	resinfo_indexable(texture2d)(float,float,float,float) ${dim}.xyyy, l(0), t69.xyzw\n
; ;\t  max ${dim}.xy, ${ini}.xx, ${dim}.xy\n
; \t	if_nz ${dim}.xy\n
; \t\t    sample_aoffimmi_indexable(1,1,1)(texture2d)(float,float,float,float) ${tex69}.xyzw, ${texcoord}.xyzw, t69.xyzw, s15\n
; \t\t    mov o5.x, ${tex69}.x\n
; \t  endif\n
; endif\n
; ret
