namespace = TexFx

[CommandListTexFxApplyTransparency]
if $texfx_on && !$drawn
    if ResourceFakeo0.f !== null
        $drawn = 1
        ;run = CommandListBackupOutputs

        run = BuiltInCommandListUnbindAllRenderTargets
        o0 = set_viewport bb
        ps-t2 = ResourceLatestoD
        x70 = 1
        ps-t0 = ResourceFakeo1.B
        ps-t1 = ResourceFakeo6.B
        ps-t3 = ResourceFakeoD.B
        run = CustomShaderShowShaderOutput
        x70 = 2
        ps-t0 = ResourceFakeo1.F
        ps-t1 = ResourceFakeo6.F
        ps-t3 = ResourceFakeoD.F
        run = CustomShaderShowShaderOutput

        ;run = CommandListRestoreOutputs
    endif
endif

; [ShaderRegexPatchForPostIBs]
; ; Investigate the downsides to this.
; shader_model = vs_4_0 vs_4_1 vs_5_0 vs_5_1
; if $costume_mods
;     post checktextureoverride = ib
; endif

[TextureOverrideAllIBTemp]
match_bind_flags = index_buffer
match_priority = -9999
ps-t69 = null
ps-t70 = null
; Trying a bit too hard to make everything trasnparent.
; $alpha = 0.5
; run = CommandListBatch.Pre
; if $internal_control
;     handling = skip
;     run = CommandListSetIV
;     ps-t69 = Resource\VirTex\LightMap
;     if $back_render
;         run = CustomShaderBack
;     endif
;     run = CustomShaderFront
;     x70 = 0
;     draw = from_caller
; endif
; run = CommandListBatch.Post
post ps-t69 = null
post ps-t70 = null

; [TextureOverride_o0]
; match_type = Texture2D
; match_format = R10G10B10A2_TYPELESS
; match_bind_flags = shader_resource render_target
; filter_index = 7778.12

; [TextureOverride_o1/o2]
; match_type = Texture2D
; match_format = R8G8B8A8_TYPELESS
; match_bind_flags = shader_resource render_target
; filter_index = 334.22

[TextureOverride_o3/4/5]
match_type = Texture2D
match_format = R8_TYPELESS
match_bind_flags = shader_resource render_target
filter_index = 1334.76


[CustomShaderShowShaderOutput]
vs = DebugShaderOutput.hlsl
ps = DebugShaderOutput.hlsl
x0 = RES_WIDTH
y0 = RES_HEIGHT
z0 = 0
w0 = 1
x1 = 1
max_executions_per_frame = 2
;cull = back
alpha_to_coverage = 0
sample_mask = ffffffff
blend_factor[0] = 0
blend_factor[1] = 0
blend_factor[2] = 0
blend_factor[3] = 0
blend = ADD SRC_ALPHA INV_SRC_ALPHA
alpha = ADD ONE ZERO
cull = back
topology = TRIANGLE_LIST
o0 = set_viewport bb
draw = 3, 0

[CustomShader_MERGE]
vs = MERGE.hlsl
ps = MERGE.hlsl
max_executions_per_frame = 1
topology = triangle_strip
cull = none

[ResourceLatestoD]
[CommandList_DiffuseSecondDraw]
run = CommandListBatch.Pre

if $internal_control
    run = CommandListSetIV
    if $back_render
        run = CustomShaderBack
    endif
    run = CustomShaderFront
    x70 = 0
endif

run = CommandListBatch.Post

[CommandListBatch.Pre]
if !$internal_control
    if (($alpha > 0) || (ps-t69 !== null)) && o3 == 1334.76
        $internal_control = 1
        ResourceLatestoD = ref oD unless_null
    endif
endif
if $internal_control
    run = CommandListGetDescriptions
    run = CommandListBackupOutputs
    run = CommandListSetFlags
    ;run = CommandListSetInstanceValues
endif

[CustomShaderFront]
cull = back
front = CounterClockwise
run = CommandListPrepare.F
run = CommandListDrawIndexedAutoOrArgs

[CommandListPrepare.F]
run = BuiltInCommandListUnbindAllRenderTargets
x70 = 2
o0 = ref ResourceFakeo0.F
o1 = ref ResourceFakeo1.F
o2 = ref ResourceFakeo2.F
o3 = ref ResourceFakeo3.F
o4 = ref ResourceFakeo4.F
o5 = ref ResourceFakeo5.F
o6 = ref ResourceFakeo6.F
oD = ref ResourceFakeoD.F

[CustomShaderBack]
cull = back
front = Clockwise
run = CommandListPrepare.B
run = CommandListDrawIndexedAutoOrArgs

[CommandListPrepare.B]
run = BuiltInCommandListUnbindAllRenderTargets
x70 = 1
o0 = ref ResourceFakeo0.B
o1 = ref ResourceFakeo1.B
o2 = ref ResourceFakeo2.B
o3 = ref ResourceFakeo3.B
o4 = ref ResourceFakeo4.B
o5 = ref ResourceFakeo5.B
o6 = ref ResourceFakeo6.B
oD = ref ResourceFakeoD.B

[CommandListDrawIndexedAutoOrArgs]
if $use_default_shader > -1
    if INSTANCE_COUNT > 0
        drawindexedinstanced = auto
    else
        drawindexed = auto
    endif
elif $_1
    run = CommandListDrawFromVars
else
    draw = from_caller
endif

[CommandListBatch.Post]
if $internal_control
    $internal_control = 0
    run = BuiltInCommandListUnbindAllRenderTargets
    run = CommandListRestoreOutputs
endif

[CommandListDrawFromVars]
local $_4 = INSTANCE_COUNT
$_4 = ($_4 == 0) + $_4
drawindexedinstanced = $_1, $_4, $_2, $_3, FIRST_INSTANCE

[CommandListClearDrawArgs]
$_1 = 0
$_2 = 0
$_3 = 0

[CommandListGetDescriptions]
if ResourceFakeo0.F === null
    ResourceFakeo0.F = copy_desc o0 unless_null
    ResourceFakeo1.F = copy_desc o1 unless_null
    ResourceFakeo2.F = copy_desc o2 unless_null
    ResourceFakeo3.F = copy_desc o3 unless_null
    ResourceFakeo4.F = copy_desc o4 unless_null
    ResourceFakeo5.F = copy_desc o5 unless_null
    ResourceFakeo6.F = copy_desc o1 unless_null
    ResourceFakeoD.F = copy_desc oD unless_null
    if $back_render
        ResourceFakeo0.B = copy_desc o0 unless_null
        ResourceFakeo1.B = copy_desc o1 unless_null
        ResourceFakeo2.B = copy_desc o2 unless_null
        ResourceFakeo3.B = copy_desc o3 unless_null
        ResourceFakeo4.B = copy_desc o4 unless_null
        ResourceFakeo5.B = copy_desc o5 unless_null
        ResourceFakeo6.B = copy_desc o1 unless_null
        ResourceFakeoD.B = copy_desc oD unless_null
    endif
endif

[CommandListDumpFakes]
dump = ResourceFakeo0.F dds
dump = ResourceFakeo1.F dds
dump = ResourceFakeo2.F dds
dump = ResourceFakeo3.F dds
dump = ResourceFakeo4.F dds
dump = ResourceFakeo5.F dds
dump = ResourceFakeo6.F dds
dump = ResourceFakeoD.F dds
dump = ResourceFakeo0.B dds
dump = ResourceFakeo1.B dds
dump = ResourceFakeo2.B dds
dump = ResourceFakeo3.B dds
dump = ResourceFakeo4.B dds
dump = ResourceFakeo5.B dds
dump = ResourceFakeo6.B dds
dump = ResourceFakeoD.B dds

[CommandListClearFakes]
ResourceFakeo0.F = null
clear = ResourceFakeo1.F
clear = ResourceFakeo2.F
clear = ResourceFakeo3.F
clear = ResourceFakeo4.F
clear = ResourceFakeo5.F
clear = ResourceFakeo6.F
clear = ResourceFakeoD.F
clear = ResourceFakeo0.B
clear = ResourceFakeo1.B
clear = ResourceFakeo2.B
clear = ResourceFakeo3.B
clear = ResourceFakeo4.B
clear = ResourceFakeo5.B
clear = ResourceFakeo6.B
clear = ResourceFakeoD.B

[CommandListBackupOutputs]
ResourceTempo0 = ref o0
ResourceTempo1 = ref o1
ResourceTempo2 = ref o2
ResourceTempo3 = ref o3
ResourceTempo4 = ref o4
ResourceTempo5 = ref o5
ResourceTempoD = ref oD

[CommandListRestoreOutputs]
o0 = ref ResourceTempo0
o1 = ref ResourceTempo1
o2 = ref ResourceTempo2
o3 = ref ResourceTempo3
o4 = ref ResourceTempo4
o5 = ref ResourceTempo5
oD = ref ResourceTempoD

[ResourceTempo0]
max_copies_per_frame = 1
[ResourceTempo1]
max_copies_per_frame = 1
[ResourceTempo2]
max_copies_per_frame = 1
[ResourceTempo3]
max_copies_per_frame = 1
[ResourceTempo4]
max_copies_per_frame = 1
[ResourceTempo5]
max_copies_per_frame = 1
[ResourceTempoD]
max_copies_per_frame = 1

; Front Copies
[ResourceFakeo0.F]
max_copies_per_frame = 1
[ResourceFakeo1.F]
max_copies_per_frame = 1
[ResourceFakeo2.F]
max_copies_per_frame = 1
[ResourceFakeo3.F]
max_copies_per_frame = 1
[ResourceFakeo4.F]
max_copies_per_frame = 1
[ResourceFakeo5.F]
max_copies_per_frame = 1
[ResourceFakeo6.F]
max_copies_per_frame = 1
[ResourceFakeoD.F]
max_copies_per_frame = 1
; Back Copies
[ResourceFakeo0.B]
max_copies_per_frame = 1
[ResourceFakeo1.B]
max_copies_per_frame = 1
[ResourceFakeo2.B]
max_copies_per_frame = 1
[ResourceFakeo3.B]
max_copies_per_frame = 1
[ResourceFakeo4.B]
max_copies_per_frame = 1
[ResourceFakeo5.B]
max_copies_per_frame = 1
[ResourceFakeo6.B]
max_copies_per_frame = 1
[ResourceFakeoD.B]
max_copies_per_frame = 1
