namespace = TexFx

[Present]
if $texfx_on
    if FRAME_ANALYSIS
        run = CommandListDumpFakes
    endif
    run = CommandListClearFakes
endif

[Present]
post w100 = 0
post w101 = 0
post w102 = 0

; [ShaderOverrideUI Detect66]
; ; Primary UI shader
; hash = 04911d8f38cd5d4b
; ;vs = f61f9bc2a15bedef
; allow_duplicate_hash = overrule
; ;handling = skip
; if $texfx_on
;     run = CustomShaderShowShaderOutput
; endif

[ShaderOverrideUI Detect1]
;vs=45839dba3e0ad5df-ps=497fbaf2ddf69c12
hash = 45839dba3e0ad5df
allow_duplicate_hash = overrule
$on = 0
w101 = 77

[ShaderOverrideUI Detect3]
; Depth to o0, normals to o1, luminance to o2
; vs=06358d4974729bc5-ps=ce690b346a8c215b
hash = ce690b346a8c215b
allow_duplicate_hash = overrule
analyse_options = dump_tex dump_rt dds
$on = 0
w102 = 88



[TextureOverride_o0]
match_type = Texture2D
match_format = R10G10B10A2_TYPELESS
match_height = height
match_width = width
match_bind_flags = shader_resource render_target

if $detect_o0_in_t4 == 200
    ;ps-t = ResourceTempo1
    ;analyse_options = dump_rt dump_tex dds

elif $detect_o0_in_t4 == 500
    $detect_o0_in_t4 = 200
endif

; this = null

[TextureOverride_o1/o2]
match_type = Texture2D
match_format = R8G8B8A8_TYPELESS
match_height = height
match_width = width
match_bind_flags = shader_resource render_target
filter_index = 334.22
if $control == 3
    ; x101 = 8
    ; run = CommandListDumpFakes
    ; handling = skip
    ; ps-t2 = ResourceTempo0
    ; ps-t3 = ResourceTempo1
    ; ps-t4 = ResourceTempo2

    ; ps-t6 = ResourceTempo4
    ; oD = ResourceTempoD
    ; draw = from_caller
    ;analyse_options = dump_rt dump_tex dds
endif

; this = null

[TextureOverride_o3/4/5]
match_type = Texture2D
match_format = R8_TYPELESS
match_height = height
match_width = width
match_bind_flags = shader_resource render_target
filter_index = 1334.76
; this = null

; [TextureOverride_o3/4/5]
; match_type = Texture2D
; match_format = R8_TYPELESS
; match_height = height
; match_width = width
; match_bind_flags = shader_resource render_target

[Constants]
global $detect_o5
global $detect_o0_in_t4
global $control

[CustomShaderShowShaderOutput]
vs = DebugShaderOutput.hlsl
ps = DebugShaderOutput.hlsl
x0 = RES_WIDTH
y0 = RES_HEIGHT
z0 = 0
w0 = 1
x1 = 1
max_executions_per_frame = 2
;cull = back
alpha_to_coverage = 0
sample_mask = ffffffff
blend_factor[0] = 0
blend_factor[1] = 0
blend_factor[2] = 0
blend_factor[3] = 0
blend = ADD SRC_ALPHA INV_SRC_ALPHA
alpha = ADD ONE ZERO
cull = back
;color = src_rgb * src_alpha + dest_rgb * (1- src_alpha)
;alpha = src_alpha + dest_alpha * 0
;blend = ADD SRC_ALPHA INV_SRC_ALPHA ONE ZERO
;blend = MIN SRC_COLOR INV_SRC_ALPHA ONE ZERO
;depth_clip_enable = TRUE
topology = TRIANGLE_LIST
o0 = set_viewport bb
;vs-t0 = ResourceShaderOutput

draw = 3,0


; blend_factor[0] = 1.0
; blend_factor[1] = 0.2
; blend_factor[2] = 0.0
; blend_factor[3] = 0.2
; sample_mask = 0b1111
; mask = ff00ffff
;mask[0] = a
;mask[1] = f

; blend = ADD SRC_ALPHA INV_SRC_ALPHA
; cull = None
; front = Clockwise
; fill = Solid
; depth_enable = TRUE
; depth_write_mask = ALL
;depth_func = GREATER_EQUAL
; depth_clip_enable = FALSE


; [ShaderRegexGlobal]
; shader_model = ps_4_0 ps_4_1 ps_5_0 ps_5_1
; ;analyse_options = mono
; if o5 === -0
; ;     run = CustomShader_MERGE
; ;     if ps-t3 == 334.22
; ;         checktextureoverride = ps-t3
; ;     ; elif ps-t0 == 334.22
; ;     ;     checktextureoverride = ps-t0
; ;     ; elif ps-t1 == 334.22
; ;     ;     checktextureoverride = ps-t1
; ;     ; elif ps-t2 == 334.22
; ;     ;     checktextureoverride = ps-t2
; ;     ; elif ps-t3 == 334.22
; ;     ;     checktextureoverride = ps-t3

; ;     endif
; endif
; run = CommandListResetResources

; ;     $detect_o0_in_t4 = 0
; ; endif

[Resource_MERGEo0]
[Resource_MERGEo1]
[Resource_MERGEo2]
[Resource_MERGEoD]
[Resource_MERGEp1]

[CustomShader_MERGE]
vs = MERGE.hlsl
ps = MERGE.hlsl
max_executions_per_frame = 1
topology = triangle_strip
cull = none

[ResourceLatestoD]
[CommandList_DiffuseSecondDraw]
local $x69 = x69
Run = CommandListBatch.Pre
;run = CommandListDrawIndexedAutoOrArgs
x101 = 610
;if o3 == 1334.76

if o3 == 1334.76
    ;run = CommandListDrawIndexedAutoOrArgs
    x70 = 1
    run = CustomShaderBack
    x70 = 2
    run = CustomShaderFront

else
    x101 = 614
    run = CommandListDrawIndexedAutoOrArgs
endif

run = CommandListBatch.Post
x69 = $x69

[CommandListBatch.Pre]
$ps = ps
run = CommandListSetInstanceValues
run = CommandListGetDescriptions
run = CommandListBackupOutputs
x100 = $ps
x69 = 5.0
;ps-t69 = null
;run = CommandListUnbindAllRenderTargets
if $ps == 037730.555
    ResourceLatestoD = ref oD unless_null
endif




[CustomShaderFront]
cull = back
front = CounterClockwise
run = BuiltInCommandListUnbindAllRenderTargets
o0 = ref ResourceFakeo0.F
o1 = ref ResourceFakeo1.F
o2 = ref ResourceFakeo2.F
o3 = ref ResourceFakeo3.F
o4 = ref ResourceFakeo4.F
o5 = ref ResourceFakeo5.F
o6 = ref ResourceFakeo6.F
oD = ref ResourceFakeoD.F
ps-t72 = copy ResourceFakeo6.F
run = CommandListDrawIndexedAutoOrArgs

[CustomShaderBack]
cull = back
front = Clockwise
run = BuiltInCommandListUnbindAllRenderTargets
o0 = ref ResourceFakeo0.B
o1 = ref ResourceFakeo1.B
o2 = ref ResourceFakeo2.B
o3 = ref ResourceFakeo3.B
o4 = ref ResourceFakeo4.B
o5 = ref ResourceFakeo5.B
o6 = ref ResourceFakeo6.B
oD = ref ResourceFakeoD.B
ps-t72 = copy ResourceFakeo6.B
run = CommandListDrawIndexedAutoOrArgs

[CommandListDrawIndexedAutoOrArgs]
if $use_default_shader > -1
    if INSTANCE_COUNT > 0
        drawindexedinstanced = auto
    else
        drawindexed = auto
    endif
else
    run = CommandListDrawFromVars
endif

[CommandListBatch.Post]
run = BuiltInCommandListUnbindAllRenderTargets
ps-t72 = null
run = CommandListRestoreOutputs

[CommandListDrawFromVars]
if $_1
    local $_4 = INSTANCE_COUNT
    $_4 = ($_4 == 0) + $_4
    drawindexedinstanced = $_1, $_4, $_2, $_3, FIRST_INSTANCE
endif

[CommandListClearDrawArgs]
$_1 = 0
$_2 = 0
$_3 = 0

[CommandListGetDescriptions]
if ResourceFakeo0.F === null
    ResourceFakeo0.F = copy_desc o0 unless_null
    ResourceFakeo1.F = copy_desc o1 unless_null
    ResourceFakeo2.F = copy_desc o2 unless_null
    ResourceFakeo3.F = copy_desc o3 unless_null
    ResourceFakeo4.F = copy_desc o4 unless_null
    ResourceFakeo5.F = copy_desc o5 unless_null
    ResourceFakeo6.F = copy_desc o1 unless_null
    ResourceFakeoD.F = copy_desc oD unless_null
    ResourceFakeo0.B = copy_desc o0 unless_null
    ResourceFakeo1.B = copy_desc o1 unless_null
    ResourceFakeo2.B = copy_desc o2 unless_null
    ResourceFakeo3.B = copy_desc o3 unless_null
    ResourceFakeo4.B = copy_desc o4 unless_null
    ResourceFakeo5.B = copy_desc o5 unless_null
    ResourceFakeo6.B = copy_desc o1 unless_null
    ResourceFakeoD.B = copy_desc oD unless_null
endif

[CommandListDumpFakes]
dump = ResourceFakeo0.F dds
dump = ResourceFakeo1.F dds
dump = ResourceFakeo2.F dds
dump = ResourceFakeo3.F dds
dump = ResourceFakeo4.F dds
dump = ResourceFakeo5.F dds
dump = ResourceFakeo6.F dds
dump = ResourceFakeoD.F dds
dump = ResourceFakeo0.B dds
dump = ResourceFakeo1.B dds
dump = ResourceFakeo2.B dds
dump = ResourceFakeo3.B dds
dump = ResourceFakeo4.B dds
dump = ResourceFakeo5.B dds
dump = ResourceFakeo6.B dds
dump = ResourceFakeoD.B dds

[CommandListClearFakes]
ResourceFakeo0.F = null
clear = ResourceFakeo1.F
clear = ResourceFakeo2.F
clear = ResourceFakeo3.F
clear = ResourceFakeo4.F
clear = ResourceFakeo5.F
clear = ResourceFakeo6.F
clear = ResourceFakeoD.F
clear = ResourceFakeo0.B
clear = ResourceFakeo1.B
clear = ResourceFakeo2.B
clear = ResourceFakeo3.B
clear = ResourceFakeo4.B
clear = ResourceFakeo5.B
clear = ResourceFakeo6.B
clear = ResourceFakeoD.B

[CommandListBackupOutputs]
ResourceTempo0 = ref o0
ResourceTempo1 = ref o1
ResourceTempo2 = ref o2
ResourceTempo3 = ref o3
ResourceTempo4 = ref o4
ResourceTempo5 = ref o5
ResourceTempoD = ref oD

[CommandListRestoreOutputs]
o0 = ref ResourceTempo0
o1 = ref ResourceTempo1
o2 = ref ResourceTempo2
o3 = ref ResourceTempo3
o4 = ref ResourceTempo4
o5 = ref ResourceTempo5
oD = ref ResourceTempoD

[ResourceTempo0]
max_copies_per_frame = 1
[ResourceTempo1]
max_copies_per_frame = 1
[ResourceTempo2]
max_copies_per_frame = 1
[ResourceTempo3]
max_copies_per_frame = 1
[ResourceTempo4]
max_copies_per_frame = 1
[ResourceTempo5]
max_copies_per_frame = 1
[ResourceTempoD]
max_copies_per_frame = 1

[ResourceFakeo0.F]
max_copies_per_frame = 1
[ResourceFakeo1.F]
max_copies_per_frame = 1
[ResourceFakeo2.F]
max_copies_per_frame = 1
[ResourceFakeo3.F]
max_copies_per_frame = 1
[ResourceFakeo4.F]
max_copies_per_frame = 1
[ResourceFakeo5.F]
max_copies_per_frame = 1
[ResourceFakeo6.F]
max_copies_per_frame = 1
[ResourceFakeoD.F]
max_copies_per_frame = 1
[ResourceFakeo0.B]
max_copies_per_frame = 1
[ResourceFakeo1.B]
max_copies_per_frame = 1
[ResourceFakeo2.B]
max_copies_per_frame = 1
[ResourceFakeo3.B]
max_copies_per_frame = 1
[ResourceFakeo4.B]
max_copies_per_frame = 1
[ResourceFakeo5.B]
max_copies_per_frame = 1
[ResourceFakeo6.B]
max_copies_per_frame = 1
[ResourceFakeoD.B]
max_copies_per_frame = 1
