namespace = TexFx

[Present]
if $texfx_on
    if FRAME_ANALYSIS
        run = CommandListDumpFakes
    endif
    run = CommandListClearFakes
endif

[Present]
post w100 = 0
post w101 = 0
post w102 = 0

; [ShaderOverrideUI Detect66]
; ; Primary UI shader
; hash = 04911d8f38cd5d4b
; ;vs = f61f9bc2a15bedef
; allow_duplicate_hash = overrule
; ;handling = skip
; if $texfx_on
;     run = CustomShaderShowShaderOutput
; endif

[ShaderOverrideUI Detect1]
;vs=45839dba3e0ad5df-ps=497fbaf2ddf69c12
hash = 45839dba3e0ad5df
allow_duplicate_hash = overrule
$on = 0
w101 = 77

[ShaderOverrideUI Detect3]
; Depth to o0, normals to o1, luminance to o2
; vs=06358d4974729bc5-ps=ce690b346a8c215b
hash = ce690b346a8c215b
allow_duplicate_hash = overrule
analyse_options = dump_tex dump_rt dds
$on = 0
w102 = 88



[TextureOverride_o0]
match_type = Texture2D
match_format = R10G10B10A2_TYPELESS
match_height = height
match_width = width
match_bind_flags = shader_resource render_target

if $detect_o0_in_t4 == 200
    ;ps-t = ResourceTempo1
    ;analyse_options = dump_rt dump_tex dds

elif $detect_o0_in_t4 == 500
    $detect_o0_in_t4 = 200
endif

; this = null

[TextureOverride_o1/o2]
match_type = Texture2D
match_format = R8G8B8A8_TYPELESS
match_height = height
match_width = width
match_bind_flags = shader_resource render_target
filter_index = 334.22
if $control == 3
    ; x101 = 8
    ; run = CommandListDumpFakes
    ; handling = skip
    ; ps-t2 = ResourceTempo0
    ; ps-t3 = ResourceTempo1
    ; ps-t4 = ResourceTempo2

    ; ps-t6 = ResourceTempo4
    ; oD = ResourceTempoD
    ; draw = from_caller
    ;analyse_options = dump_rt dump_tex dds
endif

; this = null

[TextureOverride_o3/4/5]
match_type = Texture2D
match_format = R8_TYPELESS
match_height = height
match_width = width
match_bind_flags = shader_resource render_target
; this = null

; [TextureOverride_o3/4/5]
; match_type = Texture2D
; match_format = R8_TYPELESS
; match_height = height
; match_width = width
; match_bind_flags = shader_resource render_target

[Constants]
global $detect_o5
global $detect_o0_in_t4
global $control

[CustomShaderShowShaderOutput]
vs = DebugShaderOutput.hlsl
ps = DebugShaderOutput.hlsl
x0 = RES_WIDTH
y0 = RES_HEIGHT
z0 = 0
w0 = 1
x1 = 1
max_executions_per_frame = 1
cull = none
;blend = ADD SRC_ALPHA INV_SRC_ALPHA ONE ZERO
;color = src_rgb * src_alpha + dest_rgb * (1- src_alpha)
;alpha = src_alpha + dest_alpha * 0
blend = ADD SRC_ALPHA INV_SRC_ALPHA ONE ZERO
;blend = MIN SRC_COLOR INV_SRC_ALPHA ONE ZERO
topology = TRIANGLE_LIST
o0 = set_viewport bb
;vs-t0 = ResourceShaderOutput
ps-t0 = ResourceFakeo1
ps-t1 = ResourceFakeo6
ps-t2 = ResourceLatestoD
ps-t3 = ResourceFakeoD
draw = 3,0


; [ShaderRegexGlobal]
; shader_model = ps_4_0 ps_4_1 ps_5_0 ps_5_1
; ;analyse_options = mono
; if o5 === -0
; ;     run = CustomShader_MERGE
; ;     if ps-t3 == 334.22
; ;         checktextureoverride = ps-t3
; ;     ; elif ps-t0 == 334.22
; ;     ;     checktextureoverride = ps-t0
; ;     ; elif ps-t1 == 334.22
; ;     ;     checktextureoverride = ps-t1
; ;     ; elif ps-t2 == 334.22
; ;     ;     checktextureoverride = ps-t2
; ;     ; elif ps-t3 == 334.22
; ;     ;     checktextureoverride = ps-t3

; ;     endif
; endif
; run = CommandListResetResources

; ;     $detect_o0_in_t4 = 0
; ; endif

[Resource_MERGEo0]
[Resource_MERGEo1]
[Resource_MERGEo2]
[Resource_MERGEoD]
[Resource_MERGEp1]

[CustomShader_MERGE]
vs = MERGE.hlsl
ps = MERGE.hlsl
max_executions_per_frame = 1
topology = triangle_strip
cull = none

[ResourceLatestoD]
[CommandList_DiffuseSecondDraw]
local $x69 = x69
Run = CommandListBatch.Pre
run = CommandListDrawIndexedAutoOrArgs
run = CommandListBatch.Post
x69 = $x69

[CommandListBatch.Pre]
$ps = ps
run = CommandListSetInstanceValues
run = CommandListGetDescriptions
run = CommandListBackupOutputs
x100 = $ps
x69 = 5.0
;ps-t69 = null
;run = CommandListUnbindAllRenderTargets
if $ps == 037730.555
    ResourceLatestoD = ref oD unless_null
endif
o0 = ref ResourceFakeo0
o1 = ref ResourceFakeo1
o2 = ref ResourceFakeo2
o3 = ref ResourceFakeo3
o4 = ref ResourceFakeo4
o5 = ref ResourceFakeo5
o6 = ref ResourceFakeo6
oD = ref ResourceFakeoD

[CommandListDrawIndexedAutoOrArgs]
if $use_default_shader > -1
    if INSTANCE_COUNT > 0
        drawindexedinstanced = auto
    else
        drawindexed = auto
    endif
else
    run = CommandListDrawFromVars
endif
    
[CommandListBatch.Post]
run = CommandListUnbindAllRenderTargets
o6 = null
run = CommandListRestoreOutputs

[CommandListDrawFromVars]
if $_1
    local $_4 = INSTANCE_COUNT 
    $_4 = ($_4 == 0) + $_4
    drawindexedinstanced = $_1, $_4, $_2, $_3, FIRST_INSTANCE
endif

[CommandListClearDrawArgs]
$_1 = 0
$_2 = 0
$_3 = 0

[CommandListGetDescriptions]
if ResourceFakeo0 === null
    ResourceFakeo0 = copy_desc o0 unless_null
    ResourceFakeo1 = copy_desc o1 unless_null
    ResourceFakeo2 = copy_desc o2 unless_null
    ResourceFakeo3 = copy_desc o3 unless_null
    ResourceFakeo4 = copy_desc o4 unless_null
    ResourceFakeo5 = copy_desc o5 unless_null
    ResourceFakeo6 = copy_desc o1 unless_null
    ResourceFakeoD = copy_desc oD unless_null
endif

[CommandListDumpFakes]
dump = ResourceFakeo0 dds
dump = ResourceFakeo1 dds
dump = ResourceFakeo2 dds
dump = ResourceFakeo3 dds
dump = ResourceFakeo4 dds
dump = ResourceFakeo5 dds
dump = ResourceFakeo6 dds
dump = ResourceFakeoD dds

[CommandListClearFakes]
ResourceFakeo0 = null
clear = ResourceFakeo1
clear = ResourceFakeo2
clear = ResourceFakeo3
clear = ResourceFakeo4
clear = ResourceFakeo5
clear = ResourceFakeo6
clear = ResourceFakeoD

[CommandListBackupOutputs]
ResourceTempo0 = ref o0
ResourceTempo1 = ref o1
ResourceTempo2 = ref o2
ResourceTempo3 = ref o3
ResourceTempo4 = ref o4
ResourceTempo5 = ref o5
ResourceTempoD = ref oD

[CommandListRestoreOutputs]
o0 = ref ResourceTempo0
o1 = ref ResourceTempo1
o2 = ref ResourceTempo2
o3 = ref ResourceTempo3
o4 = ref ResourceTempo4
o5 = ref ResourceTempo5
oD = ref ResourceTempoD

[ResourceTempo0]
max_copies_per_frame = 1
[ResourceTempo1]
max_copies_per_frame = 1
[ResourceTempo2]
max_copies_per_frame = 1
[ResourceTempo3]
max_copies_per_frame = 1
[ResourceTempo4]
max_copies_per_frame = 1
[ResourceTempo5]
max_copies_per_frame = 1
[ResourceTempoD]
max_copies_per_frame = 1

[ResourceFakeo0]
max_copies_per_frame = 1
[ResourceFakeo1]
max_copies_per_frame = 1
[ResourceFakeo2]
max_copies_per_frame = 1
[ResourceFakeo3]
max_copies_per_frame = 1
[ResourceFakeo4]
max_copies_per_frame = 1
[ResourceFakeo5]
max_copies_per_frame = 1
[ResourceFakeo6]
max_copies_per_frame = 1
[ResourceFakeoD]
max_copies_per_frame = 1