namespace = TexFx

[ShaderRegexOutlineTransparency]
shader_model = ps_4_0 ps_5_0
temps = ini69 ini70 tex69 tex70 dim texcoord msg

; Regex Match ---------------------------------------
;Match Outline
[ShaderRegexOutlineTransparency.Pattern]
(?(DEFINE)
    (?'fl'-?\d+\.?\d{0,6})
    (?'cmp'\.[xyzw]{1,4})
    (?'l1'l\((?&fl)\))
    (?'l4'l\((?&fl), (?&fl), (?&fl), (?&fl)\))
    (?'r'-?r\d\d?\.[xyzw]{1,4})
    (?'v'-?v\d\d?\.[xyzw]{1,4})
    (?'rv'-?[rv]\d\d?\.[xyzw]{1,4})
    (?'cb'-?cb\d\[\d+\]\.\w{1,4})
    (?'icb'icb\[-?r\d\d?\.[xyzw]{1,4}\h\+\h-?\d+\]\.[xyzw]{1,4})
    (?'dcl2d'dcl_resource_texture2d \(float,float,float,float\) t\d\d?\n)
    (?'dclin'dcl_input_ps[\w\h]+(?&v)\n)
    (?'s2d'sample_[b_]{0,2}(aoffimmi_)?indexable(\(\d,\d,\d\))?\(texture2d\)\(float,float,float,float\))
)(?s)(?'MatchOutline'
dcl_output o0\.xyzw\n
dcl_output o1\.xyzw\n
dcl_output o2\.xyzw\n
dcl_output o3\.x\n
dcl_output o4\.x\n
dcl_output o5\.x\n
.*)
(?'ModestyA'\h*lt\h(?&r),\h((?&cb)|(?&r)),\h)l\(0\.950000\)\n
(?'ModestyB'
^\h*if_nz (?&r)\n
^\h+div (?&r), (?&v), (?&v)\n
^\h+mul (?&r), (?&r), (?&cb)\n
^\h+mul (?&r), (?&r), (?&l4)\n
^\h+ge (?&r), (?&r), (?&r)\n
^\h+frc (?&r), \|(?&r)\|\n
^\h+movc (?&r), (?&r), (?&r), (?&r)\n
^\h+mul (?&r), (?&r), (?&l4)\n
^\h+ftou (?&r), (?&r)\n
^\h+dp\d (?&r), (?&cb), (?&icb)\n
^\h+dp\d (?&r), (?&cb), (?&icb)\n
^\h+dp\d (?&r), (?&cb), (?&icb)\n
^\h+dp\d (?&r), (?&cb), (?&icb)\n
^\h+dp\d (?&r), (?&r), (?&icb)\n
^\h+mad (?&r), ((?&cb)|(?&r)), (?&l1), (?&r)\n
^\h+add (?&r), (?&r), (?&l1)\n
^\h+lt (?&r), (?&r), (?&l1)\n)
(?'Modesty'\h*discard_n?z\h(?&r)\n)
(?'TillTexcord'.*)
(?'sample'(?&s2d) (?&r), (?'TexcoordX'[r]\d\d?\.[xyz][yzw][xyz][xyz]), t[01].[xyzw]{4}, s\d(, \w\d+(\.[xyzw]{1,4})?)?$)
(?'TillSetColor'.*else\s*mov (?'color'(?&r)), v\d\.(?'cswizzle'[xyzw]{4}).*endif)
(?'TillRet'.*)
ret

; [goml]
; (?'oop'\w+\h(?'o1'o1(?&cmp))|(?'o2'o2(?&cmp))|(?'o4'o4(?&cmp)|o\d(?&cmp)),\h.+$)
; ${oop}${o1:+${o1}\n\r}${o0:+${o1}\n\r}$0


[ShaderRegexOutlineTransparency.InsertDeclarations]
dcl_input_ps_sgv constant v20.x, is_front_face
dcl_resource_texture1d (float,float,float,float) t120
dcl_resource_texture2d (float,float,float,float) t69
dcl_resource_texture2d (float,float,float,float) t70
dcl_sampler s15, mode_default

[ShaderRegexOutlineTransparency.Pattern.Replace]
${MatchOutline}
; debugging, remove outline
; discard_z l(0)\n
; Add a toggle :X so this can be enable/disabled.
ld_indexable(texture1d)(float,float,float,float) ${ini70}.xyzw, l(70,0), t120.xyzw\n
discard_nz ${ini70}.x\n
;discard_z l(0)\n
ld_indexable(texture1d)(float,float,float,float) ${ini69}.xyzw, l(69,0), t120.xyzw\n
ftou ${msg}.x, ${ini69}_abs.x\n
and ${msg}.y, ${msg}.x, l(0x20)\n
movc ${ini69}.x, ${msg}.y, l(0.10000), l(0.95)\n
${ModestyA}${ini69}.x\n
${ModestyB}
and ${msg}.z, ${msg}.x, l(0x10)\n
or ${msg}.z, ${msg}.z, ${msg}.y\n
if_nz ${msg}.z\n
	${Modesty}
endif\n
${TillTexcord}\n
mov ${texcoord}.xyzw, ${TexcoordX}\n
${sample}
${TillSetColor}\n
; Custom Outline Colors, Sponsered by Annplan.
${TexcoordX:+
and ${msg}.y, ${msg}.x, l(0x1)\n
if_nz ${msg}.y\n
\t	resinfo_indexable(texture2d)(float,float,float,float) ${dim}.xyyy, l(0), t70.xyyy\n
\t	if_nz ${dim}.xy\n
\t\t	sample_aoffimmi_indexable(1,1,1)(texture2d)(float,float,float,float) ${tex70}.xyzw, ${texcoord}.xyzw, t70.xyzw, s15\n
\t\t	mov ${color}, ${tex70}.${cswizzle}\n
;\t\t	add ${tex70}.w, ${tex70}.w, -l(0.5)\n
;\t\t	max ${tex70}.w, ${tex70}.w, l(0.0)\n
;\t\t	discard_z ${tex70}.w\n
\t	endif\n
endif\n
;mov ${texcoord}.xyzw, l(0.7,0.4,0.4,1.0)\nmov ${color}, ${texcoord}.${cswizzle}\n
;:mov ${texcoord}.xyzw, l(0.7,0.2,0.2,1.0)\nmov ${color}, ${texcoord}.${cswizzle}\n
}

${TillRet}
and ${msg}.y, ${msg}.x, l(0x1)\n
if_z ${msg}.y\n
    ; TexFx Discard Outlines
    resinfo_indexable(texture2d)(float,float,float,float) ${dim}.xyzw, l(0), t69.xyzw\n
    if_nz ${dim}.xy\n
        if_nz ${dim}.xy\n
            sample_aoffimmi_indexable(1,1,1)(texture2d)(float,float,float,float) ${tex69}.xyzw, ${texcoord}.xyzw, t69.xyzw, s15\n
; Green Channel
;
; Blue Channel
;
; Red Channel
;discard_nz l(1.0)\n
            and ${msg}.w, ${msg}.x, l(0x8)\n
            if_nz ${msg}.w\n
                eq ${tex69}.x, ${tex69}.x, l(1.0)\n
                discard_nz ${tex69}.x\n
            else\n
                discard_nz ${tex69}.x\n
                ;discard_nz v20.x\n
            endif\n
        endif\n
    endif\n
endif\n
ret
