namespace = TexFx

[TextureOverrideAllIBTemp]
match_bind_flags = index_buffer
match_priority = -9999
;y69 = -1
ps-t69 = null
ps-t70 = null
run = CommandListClearInstanceValues
[Constants]
global $drawn = 0
[Present]
post $drawn = 0
run = CommandListTexFxApplyTransparency
[ShaderRegexDiffuseUIStable]
shader_model = vs_5_0
run = CommandListTexFxApplyTransparency
[CommandListTexFxApplyTransparency]
if $texfx_on && !$drawn
    $drawn = 1
    Resource_MERGEo0 = ref o0
    Resource_MERGEoD = ref oD
    run = BuiltInCommandListUnbindAllRenderTargets
    o0 = set_viewport bb
    ps-t2 = ResourceLatestoD
    x70 = 1
    ps-t0 = ResourceFakeo1.B
    ps-t1 = copy ResourceFakeo6.B
    ps-t3 = ResourceFakeoD.B
    run = CustomShaderShowShaderOutput
    x70 = 2
    ps-t0 = ResourceFakeo1.F
    ps-t1 = copy ResourceFakeo6.F
    ps-t3 = ResourceFakeoD.F
    run = CustomShaderShowShaderOutput
    y103 = 6
    o0 = ref Resource_MERGEo0
    oD = ref Resource_MERGEoD
endif

[ShaderRegexDiffuseUIStable.Pattern]
dcl_globalFlags\hrefactoringAllowed\n
dcl_constantbuffer\hCB0\[\d+\],\himmediateIndexed\n
dcl_constantbuffer\hCB1\[\d+\],\himmediateIndexed\n
dcl_constantbuffer\hCB2\[\d+\],\himmediateIndexed\n
dcl_input\hv0\.xyzw\n
dcl_input\hv1\.xyzw\n
dcl_input\hv2\.xy\n
dcl_output_siv\ho0\.xyzw,\hposition\n
dcl_output\ho1\.xyzw\n
dcl_output\ho2\.xy\n
dcl_output\ho3\.xyzw\n
dcl_temps\h\d+\n
(?(DEFINE)
(?# end my suffering)
    (?'r'-?r\d\d?\.[xyzw]{1,4})
    (?'v'-?v\d\d?\.[xyzw]{1,4})
    (?'cb'-?cb\d\[\d+\]\.\w{1,4})
    (?'icb'icb\[-?r\d\d?\.[xyzw]{1,4}\h\+\h-?\d+\]\.[xyzw]{1,4})
    (?'f4_0'l\((0\.000000,?\h?){4}\))
    (?'f4_0_or_1_055'l\((1\.055000,?\h?|0\.000000,?\h?){4}\))
    (?'f4_0_or_0_466'l\((0\.416666657,?\h?|0\.000000,?\h?){4}\))
    (?'f4_0_or_n0_055'l\((-0\.055000,?\h?|0\.000000,?\h?){4}\))
)
mul\h(?&r),\hv0\.yyyy,\h(?&cb)\n
mad\h(?&r),\h(?&cb),\hv0\.xxxx,\h(?&r)\n
mad\h(?&r),\h(?&cb),\hv0\.zzzz,\h(?&r)\n
add\h(?&r),\h(?&r),\h(?&cb)\n
mul\h(?&r),\h(?&r),\h(?&cb)\n
mad\h(?&r),\h(?&cb),\h(?&r),\h(?&r)\n
mad\h(?&r),\h(?&cb),\h(?&r),\h(?&r)\n
mad\ho0\.xyzw,\h(?&cb),\h(?&r),\h(?&r)\n
mul\h(?&r),\hv1\.xyzw,\h(?&cb)\n
max\h(?&r),\h(?&r),\h(?&f4_0)\n
mov\ho1\.w,\h(?&r)\n
log\h(?&r),\h(?&r)\n
mul\h(?&r),\h(?&r),\h(?&f4_0_or_0_466)\n
exp\h(?&r),\h(?&r)\n
mad\h(?&r),\h(?&r),\h(?&f4_0_or_1_055),\h(?&f4_0_or_n0_055)\n
max\ho1\.xyz,\h(?&r),\h(?&f4_0)\n
mov\ho2\.xy,\hv2\.xyxx\n
mov\ho3\.xyzw,\hv0\.xyzw\n
ret
