namespace = TexFx

[ShaderRegexDiffuseTransparency]
shader_model = ps_5_0
temps = msg ini69 ini70 tex69 dim storage r0 r1 r2 texcoord
run = CommandListSetFlags
post ps-t69 = null
post ps-t70 = null
run = CommandListClearInstanceValues

;Cute regex to match (almost) every character diffuse shader and outline
[ShaderRegexDiffuseTransparency.Pattern]
(?(DEFINE)
(?# This is where the Contract Demons are stored.)
    (?'fl'-?\d+\.?\d{0,6})
    (?'cmp'\.[xyzw]{1,4})
    (?'l1'l\((?&fl)\))
    (?'l4'l\((?&fl),\h(?&fl),\h(?&fl),\h(?&fl)\))
    (?'r'-?r\d\d?\.[xyzw]{1,4})
    (?'v'-?v\d\d?\.[xyzw]{1,4})
    (?'rv'-?[rv]\d\d?\.[xyzw]{1,4})
    (?'cb'-?cb\d\[\d+\]\.[xyzw]{1,4})
    (?'icb'icb\[-?r\d\d?\.[xyzw]{1,4}\h\+\h-?\d+\]\.[xyzw]{1,4})
    (?'dcl2d'dcl_resource_texture[12dcube]{2,4}\h\(float,float,float,float\)\ht\d\d?\n)
    (?'dclin'dcl_input_ps[\w\h]+(?&v)\n)
    (?'s2d'sample_[b_]{0,2}(aoffimmi_)?indexable(\(\d,\d,\d\))?\(texture2d\)\(float,float,float,float\))
    ((?'oop'\w+\h(?'oo1'o1(?&cmp))|(?'oo2'o2(?&cmp))|(?'oo4'o4(?&cmp)|o\d(?&cmp)),\h.+))
    (?'br'(?:.*\n)*?)
    (?'r3'-?r\d\d?\.[xyzw]{3})
    (?'txcp'-?[rv]\d\d?\.[xyz][yzw][xyz][xyz])
)(?s)
(?'MatchDiffuse'
(?&dcl2d){3,}
(?&dclin){3,}
(?'backface'dcl_input_ps_sgv\hconstant\hv\d{1,2}\.x,\his_front_face\n)?
dcl_output\ho0\.xyzw\n
dcl_output\ho1\.xyzw\n
dcl_output\ho2\.xyzw\n
dcl_output\ho3\.x\n
dcl_output\ho4\.x\n
dcl_output\ho5\.x\n
dcl_temps\h\d\d?.*)
(?'ModestyA'\h*lt\h(?&r),\h((?&cb)|(?&r)),\h)l\(0\.950000\)\n
(?'ModestyB'
\h*if_nz\h(?&r)\n
\h+div\h(?&r),\h(?&v),\h(?&v)\n
\h+mul\h(?&r),\h(?&r),\h(?&cb)\n
\h+mul\h(?&r),\h(?&r),\h(?&l4)\n
\h+ge\h(?&r),\h(?&r),\h(?&r)\n
\h+frc\h(?&r),\h\|(?&r)\|\n
\h+movc\h(?&r),\h(?&r),\h(?&r),\h(?&r)\n
\h+mul\h(?&r),\h(?&r),\h(?&l4)\n
\h+ftou\h(?&r),\h(?&r)\n
\h+dp\d\h(?&r),\h(?&cb),\h(?&icb)\n
\h+dp\d\h(?&r),\h(?&cb),\h(?&icb)\n
\h+dp\d\h(?&r),\h(?&cb),\h(?&icb)\n
\h+dp\d\h(?&r),\h(?&cb),\h(?&icb)\n
\h+dp\d\h(?&r),\h(?&r),\h(?&icb)\n
\h+mad\h(?&r),\h((?&cb)|(?&r)),\h(?&l1),\h(?&r)\n
\h+add\h(?&r),\h(?&r),\h(?&l1)\n
\h+lt\h(?&r),\h(?&r),\h(?&l1)\n)
(?'Modesty'\h*discard_n?z\h(?&r)\n)
(?'TillTexcord'.*)
(?!\w+\nne+?)(?'sample'^(?&s2d)(?'clr'\h(?&r3))[xyzw]?,\h(?'txc'(?&txcp)),\ht[012]\.[xyzw]{4},\h(?'s's\d)(,\h(?'bias'((?&cb)|(?&r))))?)\n
(?'Tillo1w'.*)(?'o1w'^\h*(?'o1wop'\w+)\ho1.(?'o1c'[xyz]{1,3})?)w,\h(?'o1wreg'(?&r))\n
; (?'Tillo2w'.*)(?'o2w'^\h*(?'o2wop'\w+)\ho2.[xyz]{0,3})w,\h(?'o2wreg'(?&r))\n
(?'Tillo4'.*)(?'Bloom'^mov\ho4.x,\h)(?'o4xReg'(?&r))\n
(?'TillRet'.*)
ret

[ShaderRegexDiffuseTransparency.InsertDeclarations]
dcl_resource_texture1d (float,float,float,float) t120
dcl_resource_texture2d (float,float,float,float) t72
dcl_resource_texture2d (float,float,float,float) t69
; dcl_input_ps_siv linear noperspective v21.xy, position
; dcl_input_ps_sgv constant v20.x, is_front_face
dcl_output o6.xyzw

;Inserts a discard statement if any pixel from our ps-t69 texture is not OPAQUE
[ShaderRegexDiffuseTransparency.Pattern.Replace]
${MatchDiffuse}
ld_indexable(texture1d)(float,float,float,float) ${ini69}.xyzw, l(69,0), t120.xyzw\n
ftou ${msg}.x, ${ini69}.x\n
and ${msg}.y, ${msg}.x, l(0x20)\n
movc ${r0}.x, ${msg}.y, l(0.1), l(0.95)\n
${ModestyA}${r0}.x\n
${ModestyB}
and ${msg}.z, ${msg}.x, l(0x10)\n
or ${msg}.z, ${msg}.z, ${msg}.y\n
if_nz ${msg}.z\n
	${Modesty}
endif\n
${TillTexcord}\n
mov ${texcoord}.xyzw, ${txc}\n
${sample}\n
${clr:+
ld_indexable(texture1d)(float,float,float,float) ${ini69}.xyzw, l(69,0), t120.xyzw\n
ftou ${msg}.x, ${ini69}.x\n
and ${msg}.y, ${msg}.x, l(0x3)\n
ieq ${msg}.y, ${msg}.y, l(0x2)\n
if_nz ${msg}.y\n
resinfo_indexable(texture2d)(float,float,float,float) ${dim}.xyyy, l(0), t69.xyzw\n
    if_nz ${dim}.xyyy\n
        sample_indexable(texture2d)(float,float,float,float) ${tex69}.xyzw, ${texcoord}.xyzw, t69.xyzw, ${s}\n
; Alpha Channel (8<x<64)
        ge ${r2}.w, ${tex69}.w, l(0.03125)\n
        if_nz ${r2}.w\n
            lt ${r2}.w, ${tex69}.w, l(0.25)\n
        endif\n
        if_nz ${r2}.w\n
            ld_indexable(texture1d)(float,float,float,float) ${ini70}.xyzw, l(70,0), t120.xyzw\n
            mov ${r0}.zw, l(0.000000, 0.000000, -1.000000, 0.666667)\n
            mov ${r1}.zw, l(0.000000, 0.000000, 0.000000, -0.333333)\n
            mov ${r2}.xyz, ${clr}\n
            mov ${r0}.xy, ${r2}.zyzz\n
            mov ${r1}.xy, ${r0}.yxyy\n
            lt ${r2}.y, ${r0}.y, ${r2}.z\n
            movc ${r0}.xyzw, ${r2}.yyyy, ${r0}.xyzw, ${r1}.xyzw\n
            lt ${r1}.x, ${r2}.x, ${r0}.x\n
            mov r3.xyz, ${r0}.xywx\n
            mov r3.w, ${r2}.x\n
            mov ${r0}.xyw, r3.wywx\n
            movc ${r0}.xyzw, ${r1}.xxxx, r3.xyzw, ${r0}.xyzw\n
            min ${r1}.x, ${r0}.y, ${r0}.w\n
            add ${r1}.x, ${r0}.x, -${r1}.x\n
            mad ${r1}.y, ${r1}.x, l(6.000000), l(0.000000)\n
            add ${r0}.y, -${r0}.y, ${r0}.w\n
            div ${r0}.y, ${r0}.y, ${r1}.y\n
            add ${r0}.y, ${r0}.y, ${r0}.z\n
; HUE
            add ${r0}.z, ${ini70}.y, |${r0}.y|\n
            ge ${r0}.w, ${r0}.z, -${r0}.z\n
            frc ${r0}.z, |${r0}.z|\n
            movc ${r0}.z, ${r0}.w, ${r0}.z, -${r0}.z\n
            ge ${r0}.w, |${r0}.y|, l(0.266000)\n
            mov ${r0}.w, l(1.0)\n
            movc ${r0}.y, ${r0}.w, ${r0}.z, |${r0}.y|\n
            add ${r0}.yzw, ${r0}.yyyy, l(0.000000, 1.000000, 0.666667, 0.333333)\n
            frc ${r0}.yzw, ${r0}.yyzw\n
            mad ${r0}.yzw, ${r0}.yyzw, l(0.000000, 6.000000, 6.000000, 6.000000), l(0.000000, -3.000000, -3.000000, -3.000000)\n
            add_sat ${r0}.yzw, |${r0}.yyzw|, l(0.000000, -1.000000, -1.000000, -1.000000)\n
            add ${r0}.yzw, ${r0}.yyzw, l(0.000000, -1.000000, -1.000000, -1.000000)\n
            add ${r1}.y, ${r0}.x, l(0.000000)\n
; VAL
            add ${r0}.x, ${r0}.x, ${ini70}.w\n
            div ${r1}.x, ${r1}.x, ${r1}.y\n
; SAT
            add ${r1}.x, ${r1}.x, ${ini70}.z\n
            mad ${r0}.yzw, ${r1}.xxxx, ${r0}.yyzw, l(0.000000, 1.000000, 1.000000, 1.000000)\n
            mul ${clr}, ${r0}.yzwy, ${r0}.xxxx\n
        endif\n
    endif\n
endif\n
}
${Tillo1w}${o1wop} ${storage}.w, ${o1wreg}\n
${o1c:+${o1w}, ${o1wreg}\n}
; ${Tillo2w}${o2wop} ${storage}.y, ${o2wreg}\n
; ${o2w}, ${o2wreg}\n
${Tillo4}mov ${storage}.x, ${o4xReg}\n
${TillRet}
; EXPERIMENTAL
ld_indexable(texture1d)(float,float,float,float) ${ini69}.xyzw, l(69,0), t120.xyzw\n
ftou ${msg}.x, ${ini69}.x\n
and ${msg}.y, ${msg}.x, l(0x1)\n
if_z ${msg}.y\n
    mov ${tex69}.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)\n
    resinfo_indexable(texture2d)(float,float,float,float) ${dim}.xyyy, l(0), t69.xyzw\n
    if_nz ${dim}.xyyy\n
        sample_indexable(texture2d)(float,float,float,float) ${tex69}.xyzw, ${texcoord}.xyzw, t69.xyzw, ${s}\n
    endif\n
    movc ${tex69}.x, ${tex69}.x, ${tex69}.x, ${ini69}.w\n
    dp3 ${r0}.x, ${tex69}.xyzx, ${tex69}.xyzx\n
    ne ${r0}.x, ${r0}.x, l(0.000000)\n
    and ${r0}.x, ${r0}.x, l(0x3f800000)\n
    if_nz ${r0}.x\n
    ; Red Channel
        ; TODO: Add Override
        ; if_nz ${tex69}.x\n
            ; discard_z v20.x\n
        ; endif\n
        ld_indexable(texture1d)(float,float,float,float) ${ini70}.xyzw, l(70,0), t120.xyzw\n
        lt ${msg}.y, ${ini70}.x, l(-1.000000)\n
        movc ${ini70}.x, ${msg}.y, ${ini70}.x, l(0.0)\n
        if_nz ${ini70}.x\n
            eq ${ini70}.w, ${tex69}.x, l(0.000000)\n
            discard_nz ${ini70}.w\n
            eq ${ini70}.w, ${tex69}.x, l(1.000000)\n
            discard_nz ${ini70}.w\n
            ; if Front Face Pass

            eq ${ini70}.w, ${ini70}.x, l(-20.000000)\n
            if_z ${ini70}.w\n
                mov o6.x, ${tex69}.x\n
                mov o6.y, l(0.0)\n
                ; mad_sat ${tex69}.x, ${tex69}.x, l(0.5), l(0.0)\n
            else\n
                mov o6.y, ${tex69}.x\n
                mov o6.x, l(0.0)\n
                ; mad_sat ${tex69}.x, ${tex69}.x, l(0.5), l(0.5)\n
            endif\n
            ; mov o2.w, ${tex69}.x\n
            mov o6.w, ${tex69}.x\n
            ; mad r0.z, r0.z, l(0.5), l(0.33333)\n
            mov o6.z, l(0.0)\n
        else\n
            discard_nz ${tex69}.x\n
            ; mov o2.w, ${storage}.y\n
        endif\n
    ; Green Channel
        if_nz ${tex69}.y\n
            ; Temp glow override
            ; add storage for Glow
            mad_sat o1.w, ${tex69}.y, ${ini69}.y, ${storage}.w\n
        else\n
            mov o1.w, ${storage}.w\n
        endif\n
    ; Blue Channel
        if_nz ${tex69}.z\n
            mad_sat o4.x, ${tex69}.z, ${ini69}.z, ${storage}.x\n
        else\n
            mov o4.x, ${storage}.x\n
        endif\n
    ; Alpha Channel
    else\n
        mov o1.w, ${storage}.w\n
        ; mov o2.w, ${storage}.y\n
        mov o4.x, ${storage}.x\n
    endif\n
else\n
    mov o1.w, ${storage}.w\n
    ; mov o2.w, ${storage}.y\n
    mov o4.x, ${storage}.x\n
endif\n
ret
