namespace = TexFx

[Constants]
global $hull_hack

; Legacy Transparency Commands
[CommandListT.0]
$use_default_shader = 0
run = CommandListTransparecny_new
$use_default_shader = -1
[CommandListTransparency.0]
$use_default_shader = 0
run = CommandListTransparecny_new
$use_default_shader = -1
[CommandListT.1]
$use_default_shader = 1
run = CommandListTransparecny_new
$use_default_shader = -1
[CommandListTransparency.1]
$use_default_shader = 1
run = CommandListTransparecny_new
$use_default_shader = -1
[CommandListTransparencyNatlan]
$use_default_shader = 3
run = CommandListTransparecny_new
$use_default_shader = -1
[CommandListTransparencyNatlan.0]
$use_default_shader = 2
run = CommandListTransparecny_new
$use_default_shader = -1
[CommandListTransparencyNatlan.1]
$use_default_shader = 3
run = CommandListTransparecny_new
$use_default_shader = -1
[CommandListTNat]
$use_default_shader = 3
run = CommandListTransparecny_new
$use_default_shader = -1
[CommandListTNat.0]
$use_default_shader = 2
run = CommandListTransparecny_new
$use_default_shader = -1
[CommandListTNat.1]
$use_default_shader = 3
run = CommandListTransparecny_new
$use_default_shader = -1
[CommandListTN]
$use_default_shader = 3
run = CommandListTransparecny_new
$use_default_shader = -1
[CommandListTN.0]
$use_default_shader = 2
run = CommandListTransparecny_new
$use_default_shader = -1
[CommandListTN.1]
$use_default_shader = 3
run = CommandListTransparecny_new
$use_default_shader = -1

; Legacy Component Commands
[CommandListC.0]
run = CommandListComponent
[CommandListComponent.0]
run = CommandListComponent
[CommandListC.1]
run = CommandListComponent.1
[CommandListComponent.1]
run = CommandListComponent
[CommandListCN.0]
run = CommandListComponent
[CommandListCNat.0]
run = CommandListComponent
[CommandListComponentNatlan.0]
run = CommandListComponent
[CommandListCN]
run = CommandListComponent
[CommandListCNat]
run = CommandListComponent
[CommandListComponentNatlan]
run = CommandListComponent
[CommandListCN.1]
run = CommandListComponent
[CommandListCNat.1]
run = CommandListComponent
[CommandListComponentNatlan.1]
run = CommandListComponent

; Hull Hack
[CommandListHullHack]
[CommandListShh]
[CommandListSupHH]
[CommandListSupressHullHack]

; Default Custom Shader
; [CustomShaderTransparencyDefault.0_3.4]
; [CustomShaderTransparencyDefault.1_3.4]
; [CustomShaderTransparencyDefault.0_4.5]
; [CustomShaderTransparencyDefault.1_4.5]
; [CustomShaderTransparencyNatlan.0]
; [CustomShaderTransparencyNatlanSupressHH.0]
; [CustomShaderTransparencyNatlan.1]
; [CustomShaderTransparencyNatlanSupressHH.1]
; [CustomShaderTransparencyDefault.0]
; [CustomShaderTransparencySupressHH.0]
; [CustomShaderTransparencyDefault.1]
; [CustomShaderTransparencySupressHH.1]
; [CustomShaderTransparencyDefault.0_5_3]
; [CustomShaderTransparencySupressHH.0_5_3]
; [CustomShaderTransparencyDefault.1_5_3]
; [CustomShaderTransparencySupressHH.1_5_3]
