namespace = TexFx

[ShaderRegexOutlineTransparency]
shader_model = ps_5_0
temps = ini69 ini70 tex69 tex70 dim texcoord msg r0
run = CommandListSetFlags
ps-t69 = null
ps-t70 = null
post ps-t69 = null
post ps-t70 = null
post run = CommandListClearInstanceValues

; Regex Match ---------------------------------------
;Match Outline
[ShaderRegexOutlineTransparency.Pattern]
(?(DEFINE)
(?# This is where the Contract Demons are stored.)
    (?'fl'-?\d+\.?\d{0,6})
    (?'cmp'\.[xyzw]{1,4})
    (?'l1'l\((?&fl)\))
    (?'l4'l\((?&fl),\h(?&fl),\h(?&fl),\h(?&fl)\))
    (?'r'-?r\d\d?\.[xyzw]{1,4})
    (?'v'-?v\d\d?\.[xyzw]{1,4})
    (?'rv'-?[rv]\d\d?\.[xyzw]{1,4})
    (?'cb'-?cb\d\[\d+\]\.\w{1,4})
    (?'icb'icb\[-?r\d\d?\.[xyzw]{1,4}\h\+\h-?\d+\]\.[xyzw]{1,4})
    (?'dcl2d'dcl_resource_texture[12dcube]{2,4}\h\(float,float,float,float\)\ht\d\d?\n)
    (?'dclin'dcl_input_ps[\w\h]+(?&v)\n)
    (?'s2d'sample_[b_]{0,2}(aoffimmi_)?indexable(\(\d,\d,\d\))?\(texture2d\)\(float,float,float,float\))
)(?s)(?'MatchOutline'
dcl_output\ho0\.xyzw\n
dcl_output\ho1\.xyzw\n
dcl_output\ho2\.xyzw\n
dcl_output\ho3\.x\n
dcl_output\ho4\.x\n
dcl_output\ho5\.x\n
.*)
(?'ModestyA'\h*lt\h(?&r),\h((?&cb)|(?&r)),\h)l\(0\.950000\)\n
(?'ModestyB'
^\h*if_nz\h(?&r)\n
^\h+div\h(?&r),\h(?&v),\h(?&v)\n
^\h+mul\h(?&r),\h(?&r),\h(?&cb)\n
^\h+mul\h(?&r),\h(?&r),\h(?&l4)\n
^\h+ge\h(?&r),\h(?&r),\h(?&r)\n
^\h+frc\h(?&r),\h\|(?&r)\|\n
^\h+movc\h(?&r),\h(?&r),\h(?&r),\h(?&r)\n
^\h+mul\h(?&r),\h(?&r),\h(?&l4)\n
^\h+ftou\h(?&r),\h(?&r)\n
^\h+dp\d\h(?&r),\h(?&cb),\h(?&icb)\n
^\h+dp\d\h(?&r),\h(?&cb),\h(?&icb)\n
^\h+dp\d\h(?&r),\h(?&cb),\h(?&icb)\n
^\h+dp\d\h(?&r),\h(?&cb),\h(?&icb)\n
^\h+dp\d\h(?&r),\h(?&r),\h(?&icb)\n
^\h+mad\h(?&r),\h((?&cb)|(?&r)),\h(?&l1),\h(?&r)\n
^\h+add\h(?&r),\h(?&r),\h(?&l1)\n
^\h+lt\h(?&r),\h(?&r),\h(?&l1)\n)
(?'Modesty'\h*discard_n?z\h(?&r)\n)
(?'TillTexcord'.*)
(?'sample'(?&s2d)\h(?&r),\h(?'TexcoordX'[r]\d\d?\.[xyz][yzw][xyz][xyz]),\ht[01].[xyzw]{4},\hs\d(,\h\w\d+(\.[xyzw]{1,4})?)?$\n)
(?'TillSetColor'.*else\s*mov\h(?'color'(?&r)),\hv\d\.(?'cswizzle'[xyzw]{4}).*endif)\n
(?'TillRet'.*)
ret

[ShaderRegexOutlineTransparency.InsertDeclarations]
; dcl_input_ps_sgv constant v20.x, is_front_face
dcl_resource_texture1d (float,float,float,float) t120
dcl_resource_texture2d (float,float,float,float) t69
dcl_resource_texture2d (float,float,float,float) t70
dcl_sampler s15, mode_default

[ShaderRegexOutlineTransparency.Pattern.Replace]
${MatchOutline}
ld_indexable(texture1d)(float,float,float,float) ${ini69}.xyzw, l(69,0), t120.xyzw\n
ftou ${msg}.x, ${ini69}_abs.x\n
and ${msg}.y, ${msg}.x, l(0x1)\n
if_z ${msg}.y\n
    ld_indexable(texture1d)(float,float,float,float) ${ini70}.xyzw, l(70,0), t120.xyzw\n
    eq ${msg}.y, ${ini70}.x, l(-10.000000)\n
    eq ${msg}.z, ${ini70}.x, l(-20.000000)\n
    or ${msg}.y, ${msg}.y, ${msg}.z\n
    movc ${ini70}.x, ${msg}.y, ${ini70}.x, l(0.0)\n
    discard_nz ${ini70}.x\n
endif\n
and ${msg}.y, ${msg}.x, l(0x20)\n
movc ${ini69}.x, ${msg}.y, l(0.10000), l(0.95)\n
${ModestyA}${ini69}.x\n
${ModestyB}
and ${msg}.z, ${msg}.x, l(0x10)\n
or ${msg}.z, ${msg}.z, ${msg}.y\n
if_nz ${msg}.z\n
    ${Modesty}
endif\n
${TillTexcord}\n
mov ${texcoord}.xyzw, ${TexcoordX}\n
${sample}
${TillSetColor}\n
; Custom Outline Colors, Sponsered by Annplan.
${TexcoordX:+
and ${msg}.y, ${msg}.x, l(0x1)\n
if_z ${msg}.y\n
    resinfo_indexable(texture2d)(float,float,float,float) ${dim}.xyyy, l(0), t70.xyyy\n
    if_nz ${dim}.xy\n
        sample_aoffimmi_indexable(1,1,1)(texture2d)(float,float,float,float) ${tex70}.xyzw, ${texcoord}.xyzw, t70.xyzw, s15\n
        mov ${color}, ${tex70}.${cswizzle}\n
    endif\n
endif\n
}
${TillRet}
and ${msg}.y, ${msg}.x, l(0x1)\n
if_z ${msg}.y\n
    mov ${tex69}.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)\n
    resinfo_indexable(texture2d)(float,float,float,float) ${dim}.xyzw, l(0), t69.xyzw\n
    if_nz ${dim}.xyyy\n
        sample_indexable(texture2d)(float,float,float,float) ${tex69}.xyzw, ${texcoord}.xyzw, t69.xyzw, s15\n
    endif\n
    movc ${tex69}.x, ${tex69}.x, ${tex69}.x, ${ini69}.w\n
    dp3 ${r0}.x, ${tex69}.xyzx, ${tex69}.xyzx\n
    ne ${r0}.x, ${r0}.x, l(0.000000)\n
    and ${r0}.x, ${r0}.x, l(0x3f800000)\n
    if_nz ${r0}.x\n
; Red Channel
    ; TexFx Discard Outlines
        and ${msg}.w, ${msg}.x, l(0x8)\n
        if_nz ${msg}.w\n
            eq ${tex69}.x, ${tex69}.x, l(1.0)\n
            discard_nz ${tex69}.x\n
        else\n
            discard_nz ${tex69}.x\n
            ;discard_z v20.x\n
        endif\n
; Green Channel
;
; Blue Channel
    endif\n
endif\n
ret
