namespace = TexFx

[Present]
if $costume_mods && $texfx_on && !$drawn
    local $w = w
    local $z = z
    z = 0
    w = 1
    run = BuiltInCommandListUnbindAllRenderTargets
    o0 = set_viewport bb
    run = CommandListApplyTransparencyOverlay
    w = $w
    z = $z
endif

; [ShaderOverrideSomeParticalShader]
; hash = 20442ec3a3144c6a
; ; Ambient Leaves effect
; allow_duplicate_hash = overrule
; if $costume_mods && $texfx_on && !$drawn
;     local $w = w
;     local $z = z
;     x103 = 4
;     z = 0
;     w = 0
;     run = CommandList\TexFx\ApplyTransparencyOverlay
;     w = $w
;     z = $z
; endif

; [ShaderOverride.MenuVS.1]
; hash = 4f8eee47124e933d
; ; Menu UI VS
; allow_duplicate_hash = overrule
; if $costume_mods && $texfx_on && !$drawn
;     local $w = w
;     local $z = z
;     ; x103 = 2
;     z = 0
;     w = 1
;     run = CommandList\TexFx\ApplyTransparencyOverlay
;     w = $w
;     z = $z
; endif

; [ShaderOverride.MenuVS.2]
; hash = 000c347263bbf7b8
; ; Menu UI VS
; allow_duplicate_hash = overrule
; if $costume_mods && $texfx_on && !$drawn
;     local $w = w
;     local $z = z
;     ; x103 = 2
;     z = 0
;     w = 1
;     run = CommandList\TexFx\ApplyTransparencyOverlay
;     w = $w
;     z = $z
; endif

; [ShaderOverride.MenuVS.3]
; hash = f61f9bc2a15bedef
; ; Menu UI VS
; allow_duplicate_hash = overrule
; if $costume_mods && $texfx_on && !$drawn
;     local $w = w
;     local $z = z
;     ; x103 = 2
;     z = 0
;     w = 1
;     run = CommandList\TexFx\ApplyTransparencyOverlay
;     w = $w
;     z = $z
; endif


; [ShaderOverride.0128]
; hash = c104620e39d322af
; ; 000128-o0=3315d2b5-vs=d06e0384690257ac-ps=c104620e39d322af
; allow_duplicate_hash = overrule
; if $costume_mods && $texfx_on && !$drawn
;     local $w = w
;     local $z = z
;     ; x103 = 2
;     z = 0
;     w = 0
;     run = CommandList\TexFx\ApplyTransparencyOverlay
;     w = $w
;     z = $z
; endif

[ShaderOverride.0130]
hash = e4d5ec0fac4f9b79
; 000130-o0=3315d2b5-vs=e4d5ec0fac4f9b79-ps=42db406f60c8f33e.dsc
; Ambient Leaves effect
allow_duplicate_hash = overrule
if $costume_mods && $texfx_on && !$drawn
    local $w = w
    local $z = z
    x103 = 3
    z = 0
    w = 0
    run = CommandList\TexFx\ApplyTransparencyOverlay
    w = $w
    z = $z
endif
