namespace = TexFx

[CommandListApplyTransparencyOverlay]
if !$drawn
    local $x70 = x70
    $drawn = 1
    ps-t22 = ResourceLatestoD
    if ResourceFakeo1.B !== null
        x70 = 1
        ps-t20 = ResourceFakeo1.B
        ps-t21 = ResourceFakeo6.B
        ps-t23 = ResourceFakeoD.B
        run = CustomShaderShowShaderOutput
    endif
    x70 = 2
    ps-t20 = ResourceFakeo1.F
    ps-t21 = ResourceFakeo6.F
    ps-t23 = ResourceFakeoD.F
    run = CustomShaderShowShaderOutput
    x70 = $x70
endif

[TextureOverrideAllIBTemp]
match_bind_flags = index_buffer
match_priority = -9999
match_index_count = > 6

ps-t69 = null
ps-t70 = null
w69 = 0
run = CommandListClearIV
run = CommandListSetFlags
post w69 = 0
post ps-t69 = null
post ps-t70 = null

[TextureOverride_o3/4/5]
match_type = Texture2D
match_format = R8_TYPELESS
match_bind_flags = shader_resource render_target
filter_index = 1334.76

[CustomShaderShowShaderOutput]
vs = DebugShaderOutput.hlsl
hs = null
ds = null
gs = null
ps = DebugShaderOutput.hlsl
cs = null
alpha_to_coverage = 0
sample_mask = ffffffff
blend_factor[0] = 0
blend_factor[1] = 0
blend_factor[2] = 0
blend_factor[3] = 0
blend = ADD SRC_ALPHA INV_SRC_ALPHA
alpha = ADD ONE ZERO
cull = back
topology = TRIANGLE_LIST
draw = 3, 0

[ResourceLatestoD]
[CommandList_DiffuseSecondDraw]
local $x70 = x70
run = CommandListBatch.Pre

if $internal_control
    ; run = CommandListSetIV
    run = CommandListSetFlags
    w69 = $alpha
    $alpha = 0
    if ($back_render + $back_render_supercide) > 0
        run = CustomShaderBack
    endif
    run = CustomShaderFront
endif

run = CommandListBatch.Post
x70 = $x70

[CommandListBatch.Pre]
if !$internal_control
    if (ps-t69 !== null || $alpha) && o4 == 1334.76
        $internal_control = 1
        ResourceLatestoD = copy oD unless_null
    endif
endif
if $internal_control
    $drawn = 0
    run = CommandListGetDescriptions
    run = CommandListBackupOutputs
    ;run = CommandListSetInstanceValues
endif

[CommandListBatch.Post]
if $internal_control
    $internal_control = 0
    $back_render_supercide = 0
    $outline_mode_supercide = 0
    run = BuiltInCommandListUnbindAllRenderTargets
    ; run = CommandListClearInstanceValues
    run = CommandListRestoreOutputs
endif

[CustomShaderFront]
cull = none
front = CounterClockwise
run = CommandList\TexFx\Prepare.F
run = CommandListDrawIndexedAutoOrArgs

[CommandListPrepare.F]
run = BuiltInCommandListUnbindAllRenderTargets
x70 = -20
o0 = ref ResourceFakeo0.F
o1 = ref ResourceFakeo1.F
o2 = ref ResourceFakeo2.F
o3 = ref ResourceFakeo3.F
o4 = ref ResourceFakeo4.F
o5 = ref ResourceFakeo5.F
o6 = ref ResourceFakeo6.F
oD = ref ResourceFakeoD.F

[CustomShaderBack]
cull = back
front = Clockwise
run = CommandList\TexFx\Prepare.B
run = CommandListDrawIndexedAutoOrArgs

[CommandListPrepare.B]
run = BuiltInCommandListUnbindAllRenderTargets
x70 = -10
o0 = ref ResourceFakeo0.B
o1 = ref ResourceFakeo1.B
o2 = ref ResourceFakeo2.B
o3 = ref ResourceFakeo3.B
o4 = ref ResourceFakeo4.B
o5 = ref ResourceFakeo5.B
o6 = ref ResourceFakeo6.B
oD = ref ResourceFakeoD.B

[CommandListDrawIndexedAutoOrArgs]
if $_1
    run = CommandListDrawFromVars
elif $use_default_shader > -1
    if INSTANCE_COUNT > 0
        drawindexedinstanced = auto
    else
        drawindexed = auto
    endif
elif $use_default_shader == -10
    ; Manual path for debugging game calls.
    draw = from_caller
else
    ;draw = from_caller
endif

[CommandListDrawFromVars]
local $_4 = INSTANCE_COUNT
$_4 = ($_4 == 0) + $_4
drawindexedinstanced = $_1, $_4, $_2, $_3, FIRST_INSTANCE

[CommandListClearDrawArgs]
$_1 = 0
$_2 = 0
$_3 = 0

[CommandListGetDescriptions]
run = CommandListNullFakesIfResMismatch
if ResourceFakeo0.F === null
    ResourceFakeo0.F = copy_desc o0 unless_null
    ResourceFakeo1.F = copy_desc o1 unless_null
    ResourceFakeo2.F = copy_desc o2 unless_null
    ResourceFakeo3.F = copy_desc o3 unless_null
    ResourceFakeo4.F = copy_desc o4 unless_null
    ResourceFakeo5.F = copy_desc o5 unless_null
    ResourceFakeo6.F = copy_desc o1 unless_null
    ResourceFakeoD.F = copy_desc oD unless_null
    ResourceFakeo0.B = copy_desc o0 unless_null
    ResourceFakeo1.B = copy_desc o1 unless_null
    ResourceFakeo2.B = copy_desc o2 unless_null
    ResourceFakeo3.B = copy_desc o3 unless_null
    ResourceFakeo4.B = copy_desc o4 unless_null
    ResourceFakeo5.B = copy_desc o5 unless_null
    ResourceFakeo6.B = copy_desc o1 unless_null
    ResourceFakeoD.B = copy_desc oD unless_null
endif

[CommandListClearFakes]
if ResourceFakeo0.F !== null
    clear = ResourceFakeo0.F
    clear = ResourceFakeo1.F
    clear = ResourceFakeo2.F
    clear = ResourceFakeo3.F
    clear = ResourceFakeo4.F
    clear = ResourceFakeo5.F
    clear = ResourceFakeo6.F
    clear = ResourceFakeoD.F
    clear = ResourceFakeo0.B
    clear = ResourceFakeo1.B
    clear = ResourceFakeo2.B
    clear = ResourceFakeo3.B
    clear = ResourceFakeo4.B
    clear = ResourceFakeo5.B
    clear = ResourceFakeo6.B
    clear = ResourceFakeoD.B
endif

[CommandListNullFakesIfResMismatch]
if rt_height * rt_width != $pixels
    $pixels = rt_height * rt_width
    ResourceFakeo0.F = null
    ResourceFakeo1.F = null
    ResourceFakeo2.F = null
    ResourceFakeo3.F = null
    ResourceFakeo4.F = null
    ResourceFakeo5.F = null
    ResourceFakeo6.F = null
    ResourceFakeoD.F = null
    ResourceFakeo0.B = null
    ResourceFakeo1.B = null
    ResourceFakeo2.B = null
    ResourceFakeo3.B = null
    ResourceFakeo4.B = null
    ResourceFakeo5.B = null
    ResourceFakeo6.B = null
    ResourceFakeoD.B = null
endif

[CommandListDumpFakes]
dump = ResourceFakeo0.F dds
dump = ResourceFakeo1.F dds
dump = ResourceFakeo2.F dds
dump = ResourceFakeo3.F dds
dump = ResourceFakeo4.F dds
dump = ResourceFakeo5.F dds
dump = ResourceFakeo6.F dds
dump = ResourceFakeoD.F dds
dump = ResourceFakeo0.B dds
dump = ResourceFakeo1.B dds
dump = ResourceFakeo2.B dds
dump = ResourceFakeo3.B dds
dump = ResourceFakeo4.B dds
dump = ResourceFakeo5.B dds
dump = ResourceFakeo6.B dds
dump = ResourceFakeoD.B dds

[CommandListBackupOutputs]
ResourceTempo0 = ref o0
ResourceTempo1 = ref o1
ResourceTempo2 = ref o2
ResourceTempo3 = ref o3
ResourceTempo4 = ref o4
ResourceTempo5 = ref o5
ResourceTempoD = ref oD

[CommandListRestoreOutputs]
o0 = ref ResourceTempo0
o1 = ref ResourceTempo1
o2 = ref ResourceTempo2
o3 = ref ResourceTempo3
o4 = ref ResourceTempo4
o5 = ref ResourceTempo5
oD = ref ResourceTempoD

; Restore Resources
[ResourceTempo0]
[ResourceTempo1]
[ResourceTempo2]
[ResourceTempo3]
[ResourceTempo4]
[ResourceTempo5]
[ResourceTempoD]

; Front Copies
[ResourceFakeo0.F]
[ResourceFakeo1.F]
[ResourceFakeo2.F]
[ResourceFakeo3.F]
[ResourceFakeo4.F]
[ResourceFakeo5.F]
[ResourceFakeo6.F]
[ResourceFakeoD.F]
; Back Copies
[ResourceFakeo0.B]
[ResourceFakeo1.B]
[ResourceFakeo2.B]
[ResourceFakeo3.B]
[ResourceFakeo4.B]
[ResourceFakeo5.B]
[ResourceFakeo6.B]
[ResourceFakeoD.B]
